pluralsight/classic-design-system

- packages/build/webpack/index.js
> fix(build): webpack validation typo

- packages/site/src/common/components/color/gradient.module.css
- packages/site/src/common/components/color/swatch.module.css
- packages/site/src/common/components/side-nav/logo.module.css
- packages/site/src/components/button/index.js
- packages/site/src/components/text-styles/lists.js
- packages/site/src/home/index.js
- packages/tab/src/react/list-item.js
Increased the margin between items in tab component
> Tab spacing

- package.json
- packages/button/src/react/index.js
Changing the background color of the flat button to white with alpha, so it looks better on image backgrounds etc.
> refactor(button): make flat button hover color alpha based

- packages/drawer/src/react/index.js
adds accessibility label to drawer toggle arrow.
> fix(drawer): Add aria-label for expand/collapse

- packages/card/package.json
- packages/card/src/react/__specs__/index.spec.js
- packages/card/src/react/index.js
- packages/card/test/test-setup.js
Added an onClick to the Card.Title subcomponent in order to track onClick events on the title
> feat(card): Add onClick to Card.Title

- packages/avatar/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/avatar/src/react/__specs__/utils.spec.js
- packages/avatar/src/react/utils.js
- packages/avatar/src/vars/index.js
- packages/avatar/stories/index.js
One team found that we showed the same color over and over in a row when a list of avatars was shown for people in an alpha-ordered list.  This attempts to mix that color up.
Closes #192
> refactor(avatar): color algo for variance in alpha-order names

- packages/checkbox/src/react/index.js
- packages/form/src/react/button-row.js
- packages/form/src/react/divider.js
- packages/form/src/react/vertical-layout.js
- packages/radio/src/react/button.js
- packages/radio/src/react/group.js
- packages/textarea/src/react/index.js
- fill in title: format of "checkbox,form,radio,textarea: fix build errors"
- label: bug
- build errors encountered when running `lerna run build` from the root
- Run `lerna run build` from the root of the project
- Observe that compilation completes successfully for all packages
> checkbox,form,radio,textarea: fix build errors

- packages/dropdown/src/css/index.js
- packages/dropdown/src/react/index.js
- Resolves #244 and (duplicate) resolves #249 
- This places an invisible overlay over the whole page when the dropdown is open. The overlay intercepts clicks outside of the dropdown and closes it.
- Open the dropdown and verify clicking outside of it causes it to close
> dropdown: Close on outside click

- packages/errors/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/errors/src/react/heading.js
The contrast in the body text of the error page for the light theme meets the WCAG contrast ratio.
The white body text of the error message is low contrast compared to the light grey background.
Users will find it easier to read.  We will meet the accessibility guidelines.
> Errors: Low contrast in light theme (below WCAG contrast ratio)

- packages/text/src/react/p.js
Without Theme parent, have dark theme defaults.
No default theme given
1. Use <Text.P /> w/o <Theme /> parent, see dark text where should see colors.bone.
> text.p: no default color

- packages/site/pages/components/button.js
> site: encourage a title props when using a Button without a label

- commitlint.config.js
- packages/button/.storybook/config.js
- packages/button/package.json
- packages/button/src/react/__specs__/storyshots.spec.js
- packages/storybook-addon-center/.babelrc
- packages/storybook-addon-center/.npmignore
- packages/storybook-addon-center/.npmrc
- packages/storybook-addon-center/__mocks__/index.js
- packages/storybook-addon-center/index.js
- packages/storybook-addon-center/package.json
- packages/storybook-addon-center/src/index.js
this will allow the addon to be used by other packages in the design system
> storybook: create new package for center addon

- packages/dropdown/src/css/index.js
> Dropdown component: Fixed cursor style(pointer) for caret icon

- scripts/create-component/package-template/package.json
> feat: update template package to publish public by default

- packages/site/next.config.js
- packages/site/package.json
- packages/site/pages/components/icon.js
- packages/site/pages/components/starrating.js
- packages/site/pages/components/theme.js
- packages/site/src/ui/side-nav.js
> doc updates

- packages/site/pages/components/starrating.js
- packages/starrating/package.json
- packages/starrating/src/css/index.js
- packages/starrating/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/starrating/src/react/__specs__/index.spec.js
- packages/starrating/src/react/index.js
- packages/starrating/src/react/star.js
- packages/starrating/test/setup.js
> StarRating tweaks

- packages/starrating/src/css/index.js
- packages/starrating/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/starrating/src/react/star.js
> fix(starrating): half star was invisible in safari

- packages/site/pages/components/textinput.js
> docs(site): remove theme toggle from textinput subtle

- packages/button/src/css/index.js
- packages/button/src/react/index.js
- packages/button/stories/index.js
> update light theme disabled style

- packages/starrating/package.json
- packages/starrating/src/react/__specs__/index.spec.js
- packages/starrating/src/react/index.js
> <StarRating /> forward allowed props

- packages/site/pages/components/card.js
- packages/site/pages/design-assets.js
- packages/site/pages/roadmap.js
- packages/site/src/ui/prop-types.js
Fixes #378 
And some other proptype warnings.
> fix(site): subtle badge

- packages/starrating/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/starrating/src/react/star.js
> fix(starrating): dont pass bright prop to dom button

- packages/button/src/css/index.js
- packages/button/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/button/src/react/index.js
- packages/button/src/vars/index.js
- packages/button/stories/index.js
- packages/site/pages/components/button.js
Resolves https://github.com/pluralsight/design-system/issues/294
@dborodyansky , will you spot-check my decisions for hover styles and loading spinner styles.  I winged those (didn't see in figma).  Also, I guess, I'm bad at figma, and you can check any/all. Thanks!
> feat(button): add secondary appearance

- packages/site/pages/components/button.js
- packages/site/pages/components/tab.js
- packages/tab/.storybook/config.js
- packages/tab/package.json
- packages/tab/src/css/index.js
- packages/tab/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/tab/src/react/__stories__/index.story.js
- packages/tab/src/react/list-item.js
- packages/tab/src/react/list.js
- packages/tab/src/react/panel.js
> tab: support href, amongst other modernization refactors

- packages/site/pages/components/card.js
- packages/site/pages/components/dialog.js
- packages/site/pages/components/row.js
- fix example regression (fixes: #370)
- update durations (fixes: #391)
> minor doc updates

- packages/tooltip/src/css/index.js
- packages/tooltip/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/tooltip/src/react/index.js
- scripts/componentdev.sh
> Tooltip light theme support

- packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/dialog/src/react/__stories__/index.story.js
- packages/dialog/src/react/index.js
> feat(dialog): require a11y label if modal

- packages/site/pages/components/tab.js
> fix(site): typo

- packages/avatar/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/avatar/src/vars/index.js
> fix(avatar): ensure https for fallback pixel

- packages/actionmenu/src/css/index.js
- packages/actionmenu/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/actionmenu/src/react/__stories__/index.story.js
- packages/actionmenu/src/react/arrow.js
- packages/actionmenu/src/react/index.js
- packages/dropdown/src/css/index.js
- packages/dropdown/src/react/index.js
> Dropdown/ActionMenu: keyboard-specific focus style

- packages/datepicker/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/datepicker/src/react/index.js
> feat(datepicker): close on escape or click out

- packages/site/pages/components/dropdown.js
> refactor(site): document initial value of dropdown

- packages/site/pages/components/button.js
> feat(site): react-router with button doc

- .eslintrc.js
- packages/site/pages/components/tooltip.js
Fixes #438 
I could never make it flicker.  But I'm fine with the change.  And other people did see it.
Also updated the eslint config.  We can chat about that if you'd like.  I see the argument that inlining function binds can be unperformant.  But not if there's 3 on the page.  And it's way more convenient to be able to apply values per item in a loop like is done in the tooltip.js file here.
> site: stop tooltip flicker

- packages/site/next.config.js
I forgot to add the route 🤦‍♂️
> fix(site): add route to emptystate page

- packages/site/pages/install.js
- packages/site/src/polyfills.js
> fix(site): polyfill es6 and es7 features

- packages/datepicker/src/react/index.js
was pairing with @dannytannertantrum and tracked down(and fixed) a react key error.
> fix(datepicker): add keys to avoid errors

- packages/row/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/row/src/react/index.js
i updated the Row.Action to be a class component to resolve #451
> Row.Action ref support

- packages/icon/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/icon/src/react/__specs__/index.spec.js
- packages/icon/src/react/__stories__/index.story.js
- packages/icon/src/react/index.js
better screen reader support for custom icon labels
fixes #462
> fix(icon): aria-label should update svg attr

- packages/site/pages/components/table.js
- packages/table/.storybook/addons.js
- packages/table/.storybook/config.js
- packages/table/package.json
- packages/table/src/css/index.js
- packages/table/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/table/src/react/__specs__/storyshots.spec.js
- packages/table/src/react/__stories__/index.story.js
- packages/table/src/react/index.js
fixes: #460
- style full tables that are nested inside a Drawer
- some refactoring of the table component to bring up to current standards
TODO:
> table nested in drawer

- packages/table/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/table/src/react/index.js
> feat(table): add aria-roles to table markup

- packages/actionmenu/index.js
- packages/actionmenu/js.js
- packages/actionmenu/package.json
- packages/actionmenu/src/css/index.js
- packages/actionmenu/src/js/__specs__/index.spec.js
- packages/actionmenu/src/js/index.js
- packages/actionmenu/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/actionmenu/src/react/__stories__/index.story.js
- packages/actionmenu/src/react/index.js
> feat(actionmenu): disabled item style and focus mgmt

- packages/site/pages/components/actionmenu.js
> feat(site): docs for action menu disabled

- packages/avatar/src/css/index.js
- packages/avatar/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/avatar/src/react/__stories__/index.story.js
> fix(avatar): image always covers circle area

- packages/errors/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/errors/src/react/not-found-error-page.js
- packages/site/pages/components/errors.js
> errors: change search path

- packages/row/package.json
- packages/row/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/row/src/react/__specs__/conditional-wrap.spec.js
- packages/row/src/react/__specs__/shave.spec.js
- packages/row/src/react/__stories__/index.story.js
- packages/row/src/react/conditional-wrap.js
- packages/row/src/react/index.js
- packages/row/src/react/shave.js
- packages/site/pages/components/row.js
i had to do some awkward things to make this a non-breaking change. let's discuss
resolves #497 
Outstanding
> row: allow title to be truncated to (n) lines

- packages/site/pages/core/build.js
- packages/site/pages/install.js
finally
Fixes: #470 
And new IE support just for good measure.  Well, as good as IE can be.
> refactor(site): change postcss-cssnext to postcss-preset-env

- packages/site/pages/design-assets.js
Update `Design assets` page with new copy:
https://docs.google.com/document/d/1eRfOECiWLbSfL_yH2yyGbSAQy4JCSv7k_nWDfGdepoE/edit?usp=sharing
> site: update copy for "Design assets" page

- dangerfile.js
- package.json
`danger-plugin-toolbox` also contains a check to make sure PR's have a description: [commonPrDescription](https://github.com/sogame/danger-plugin-toolbox/blob/master/docs/validations.md#commonprdescription)
> Use "danger-plugin-toolbox" to check PR description

- packages/site/pages/components/row.js
> fix(site): row titleTruncated typo

- packages/table/src/css/index.js
- packages/table/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
> fix(table): don't smush sort icon when column header is large

- packages/button/src/css/index.js
- packages/button/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/button/src/react/__stories__/index.story.js
Fixes: #469
Chrome only; Border from stroke appearance was pushing label span down.
Existence of line height made the label fixed height.   Removing line
height seems ok, since heights are controlled by button height attribute.
> fix(button): xSmall and xmall button vert center text

- packages/datepicker/src/css/index.js
- packages/datepicker/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
Fixes: #510
In FF 66 and IE 11
> fix(datepicker): vertically align calendar button icon

- packages/actionmenu/package.json
> fix(actionmenu): put ps-design-system-prop-types in deps

- packages/table/src/react/index.js
> fix(table): column header hover state contrast ok in light theme

- packages/table/src/react/index.js
should fix the error reported here -> https://pluralsight.slack.com/archives/C70HPSJPP/p1559680472020700
> fix(table): apply theme class to cell

- packages/note/src/css/index.js
> fix(note): update metadata color on light theme

- packages/tab/index.js
- packages/tab/vars.js
Fixes: https://pluralsight.slack.com/archives/C70HPSJPP/p1561577884022900
> fix(tab): remove vars reference

- packages/site/pages/components/datawell.js
Updated examples and added some guidelines.
> docs(datawell): updated data well docs

- packages/searchinput/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/searchinput/src/react/__specs__/index.spec.js
- packages/searchinput/src/react/__stories__/index.story.js
- packages/searchinput/src/react/index.js
- packages/site/pages/components/searchinput.js
> Search input label

- packages/site/next.config.js
https://pluralsight.slack.com/archives/C70HPSJPP/p1562611989042700
> fix(site): make note page navigable

- packages/banner/package.json
- packages/banner/src/css/index.js
- packages/banner/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/banner/src/react/__stories__/index.story.js
- packages/banner/src/react/index.js
> banner: react 16

- packages/breadcrumb/package.json
- packages/breadcrumb/src/react/__specs__/index.spec.js
- packages/breadcrumb/src/react/__stories__/index.story.js
- packages/breadcrumb/src/react/index.js
> breadcrumb: react 16

- packages/site/pages/components/banner.js
- packages/site/pages/components/button.js
- packages/site/pages/components/card.js
- packages/site/pages/components/dialog.js
- packages/site/pages/components/emptystate.js
- packages/site/pages/components/form.js
- packages/site/pages/components/row.js
- packages/site/pages/components/theme.js
- packages/site/pages/components/tooltip.js
- packages/site/pages/core/color.js
- packages/site/pages/core/typography.js
- packages/site/pages/index.js
- packages/site/pages/install.js
Fixes a few misspellings and typos I found while browsing the website.
Really impressed by the work you all have done here! The documentation site looks great 👏
> site: spelling and typo fixes

- packages/site/pages/components/dropdown.js
Out of sync; now synced; n*sync
> site: match code to working example of dropdown

- packages/site/pages/components/icon.js
> fix(site): fix number of icon sizes

- packages/form/css.js
- packages/form/index.js
- packages/form/react.js
- packages/form/src/css/index.js
- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/form/src/react/button-row.js
- packages/form/src/vars/index.js
- packages/form/stories/index.js
- packages/form/vars.js
> feat(form): add align prop to ButtonRow

- packages/actionmenu/package.json
- packages/actionmenu/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/actionmenu/src/react/__specs__/index.spec.js
- packages/actionmenu/src/react/index.js
- packages/site/pages/components/actionmenu.js
Related: #590 
To support Dropdown.  Also, I think people will end up preferring a single handler like this in the API even when just using ActionMenu.
> actionmenu: add onSelect and value props

- packages/carousel/src/css/index.js
- packages/carousel/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/carousel/src/react/__stories__/index.story.js
set flex-basis and width to 0 so the flex items grow/shrink together
fix #594
> carousel: ensure all carousel items are the same width

- packages/tab/src/css/index.js
- packages/tab/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
> refactor(tab): decrease horz space between line items to 32px

- packages/site/pages/components/emptystate.js
- packages/site/pages/components/viewtoggle.js
- packages/site/src/ui/example/react.js
- packages/site/src/ui/theme-toggle.js
- packages/viewtoggle/package.json
- packages/viewtoggle/src/react/__specs__/index.spec.js
- packages/viewtoggle/src/react/__stories__/index.story.js
- packages/viewtoggle/src/react/index.js
BREAKING CHANGE: latest react (v16.8.6) is now a requirement
- upgrade to latest react patterns
- i had some trouble converting the lifecycle methods and dom interaction over. i did some crazy things but the final result ended up much simpler
- storybook and tests
> viewtoggle: use hooks and forward refs

- packages/carousel/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/carousel/src/react/__stories__/index.story.js
- packages/carousel/src/react/index.js
- packages/site/pages/components/carousel.js
- resolved #595 
- export a Carousel.Item component than can be used for individual items within the Carousel
- the Carousel.Item accepts a function as children and provides metadata in the render prop arguments
- tests and storybook
> carousel: export Carousel.Item and provide meta data

- packages/site/pages/components/dropdown.js
Verified old method still worked with new code in the example itself.  Then I changed the example to be the more traditional approach.
> docs(site): update the dropdown example for onChange/value

- packages/site/pages/patterns/iconography.js
> feat(site): add icon figma link

- packages/site/pages/components/drawer.js
> refactor(site): rm light theme section from drawer pg

- packages/carousel/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/carousel/src/react/index.js
> feat(carousel): include itemsPerPage meta data in render prop args

- packages/viewtoggle/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/viewtoggle/src/react/__stories__/index.story.js
- packages/viewtoggle/src/react/index.js
- https://pluralsight.slack.com/archives/C70HPSJPP/p1565630361034500
> fix(viewtoggle): error that happens when the active option is removed

- packages/site/pages/patterns/voice-tone.js
Added guidelines and examples for writing error messages to the Voice & Tone page.
> refactor(site): add guidelines for error messages to voice & tone page

- packages/site/package.json
was the reason for octopus breaking
> site: restore http-server needed for runtime

- packages/card/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/card/src/react/__stories__/index.story.js
- packages/card/src/react/index.js
- packages/site/pages/components/card.js
> fix(card): adds tag to small card for issue

- packages/row/src/react/index.js
- packages/row/src/react/shave.js
> refactor(row): upgrade to functional components

- packages/card/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/card/src/react/index.js
- packages/site/pages/components/card.js
an aria-label is required for screen reader accessibility
resolves #466
> feat(card): derive aria-label from title prop

- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/radio/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/radio/src/react/__specs__/index.spec.js
- packages/radio/src/react/button.js
- packages/row/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/table/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
> fix(radio): stops onSelect firing twice every time we click a radio

- packages/carousel/src/css/index.js
- packages/carousel/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
flexbox in firefox needs a min-width if you want some inner text that uses text-overflow to properly
truncate
fixes the issue reported in this thread -> https://pluralsight.slack.com/archives/C70HPSJPP/p1569616101043600
> fix(carousel): flexbox bug in ff

- packages/checkbox/src/css/index.js
- packages/checkbox/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/checkbox/src/react/__stories__/index.story.js
- packages/checkbox/src/react/index.js
- packages/site/pages/components/checkbox.js
> Checkbox: support indeterminate

- packages/layout/css.js
- packages/layout/react.js
- packages/position/js.js
- packages/position/react.js
- packages/text/react.js
> fix: cjs paths

- packages/verticaltabs/src/css/index.js
- packages/verticaltabs/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/verticaltabs/src/react/__specs__/index.spec.js
- packages/verticaltabs/src/react/__stories__/fixtures.js
- packages/verticaltabs/src/react/__stories__/index.story.js
- packages/verticaltabs/src/react/divider.js
- packages/verticaltabs/src/react/group.js
- packages/verticaltabs/src/react/index.js
- packages/verticaltabs/src/react/item.js
- packages/verticaltabs/src/react/list.js
- larger hit areas to show better focus state
- hover states
- more contrast between
- animate active state for fun
- organize components into separate files
- add a gitprime story
@sweeting i made some changes to your design to give more contrast between the active/focus/inactive states
> a couple refinements for verticaltab

- packages/position/src/react/index.js
> refactor(position): canUseDOM function updated to align with React

- packages/layout/package.json
- packages/layout/src/css/index.js
> fix(layout): now generates css and sccs files

- packages/actionmenu/src/css/index.js
- packages/actionmenu/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/actionmenu/src/react/item.js
- packages/carousel/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/dropdown/package.json
- packages/dropdown/src/css/index.js
- packages/dropdown/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/dropdown/src/react/__stories__/index.story.js
- packages/dropdown/src/react/index.js
- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/util/src/__specs__/useCombinedRefs.spec.js
- packages/util/src/index.js
- packages/util/src/useCombinedRefs.js
> fix(dropdown): dev can set width thus truncating long input & options

- packages/table/src/react/index.js
this fixes the nextjs build. i'm not actually sure why this works 🤷‍♂
> fix(table): revert to old child map style to fix doc build

- packages/emptystate/src/css/index.js
> fix(emptystate): fix undefined caption css attributes

- packages/typeahead/src/css/index.js
- packages/typeahead/src/react/menu.js
new design moves the checkmark from left to right
> feat(typeahead): position checkmark to right of label

- packages/layout/package.json
- packages/theme/package.json
> Fix build:watch cmd

- packages/featureflags/jest.config.js
- packages/featureflags/package.json
- packages/featureflags/react.d.ts
- packages/featureflags/react.js
- packages/featureflags/src/index.js
- packages/featureflags/src/react/__specs__/index.spec.js
- packages/featureflags/src/react/index.js
- packages/site/next.config.js
- packages/site/package.json
- packages/site/pages/components/featureflags.js
- packages/site/src/ui/side-nav.js
Resolves: #745 
Replaces: #756 
Reasoning for this solution in #756 comments.
> Feature Flags component

- packages/dialog/src/css/index.js
- packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/dialog/src/react/__stories__/index.story.js
@jaketrent do you think this is the right approach or did you have something different in mind
> fix(dialog): allow vert overflow/scroll

- packages/collapsible/src/index.js
> fix(collapsible): fixes animation on mount

- packages/typeahead/src/react/menu.js
> feat(typeahead): keyboard list support

- packages/table/src/css/index.js
> fix(table): fix classname typo

- packages/core/js/colors.2020.js
Can see changes on button secondary story
> feat(core): add step 1 neutrals

- packages/table/src/css/index.js
- packages/table/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/table/src/react/__stories__/index.story.js
- packages/table/src/react/index.js
> refactor(table): apply 2020 color palette

- packages/tag/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
my bad. i let a stray snapshot failure through
> test(tag): update snapshot failure

- packages/viewtoggle/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/viewtoggle/src/react/index.js
> fix(viewtoggle): remove prop themeName from dom element

- packages/starrating/src/css/index.js
- packages/starrating/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/starrating/src/react/star.js
> refactor(starrating): apply 2020 color palette

- packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/row/package.json
- packages/row/src/css/index.js
- packages/row/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/row/src/react/index.js
> refactor(row): apply 2020 color palette

- packages/linearprogress/package.json
- packages/linearprogress/src/css/index.js
- packages/linearprogress/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
> refactor(linearprogress): apply 2020 color palette

- packages/note/src/css/index.js
- packages/note/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/note/src/react/index.js
> refactor(note): apply 2020 color palette

- packages/circularprogress/package.json
- packages/circularprogress/src/css/index.js
- packages/circularprogress/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/searchinput/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
approach matching linear progress.
> refactor(circularprogress): apply 2020 color palette

- packages/emptystate/src/css/index.js
- packages/emptystate/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
> refactor(emptystate): apply 2020 color palette

- packages/dialog/package.json
- packages/dialog/src/css/index.js
- packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
> refactor(dialog): apply 2020 colors

- packages/errors/src/css/index.js
- packages/errors/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/errors/src/react/error-page.js
> refactor(errors): apply 2020 color palette

- packages/site/pages/components/icon.js
> feat(site): add sizes in px to icon docs

- packages/site/pages/core/color.js
> refactor(site): sentence case on color page headings

- packages/text/src/css/index.js
To match figma
https://www.figma.com/file/YsTklBecdddy9RZ3HXddIseD/PSDS-Web?node-id=69%3A25603
Resolves: #783
> refactor(text): tweak 2020 colors for inline code

- packages/actionmenu/src/react/item.js
> fix(actionmenu): incorrectly named prop 'css' should be 'style'

- packages/core/js/colors.2020.js
Resolves: #834
Someday the old tokens will be removed.  This moves the ones we're keeping from the old set to the new pattern.
> feat(core): add white, black, and code colors

- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/form/src/react/__stories__/index.story.js
- packages/form/src/react/vertical-layout.js
fixes bug reported here => https://pluralsight.slack.com/archives/C70HPSJPP/p1580316316035200?thread_ts=1580314925.034500&cid=C70HPSJPP
> fix(form): layout should filter out null children

- packages/position/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/tooltip/src/css/index.js
- packages/tooltip/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
> fix(tooltip): avoid blocking mouse events with tail

- packages/site/pages/components/button.js
- packages/site/pages/components/link.js
- packages/site/pages/components/text.js
- packages/site/pages/install.js
Resolves #854
Can I just say thank you for all the work that was done to clean up the DS lint errors.  So nice to edit a site page and not have lint wining about other stuff you didn't touch.
> feat(site): add featureflags peer dep doc

- packages/button/src/css/index.js
Resolves #862
Not sure why snapshot changes aren't showing up.  We'll see what CI does.  jest -u updated but I see no git diff.
> fix(button): adjust color for stroke button

- packages/dropdown/src/css/index.js
- packages/dropdown/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/dropdown/src/react/index.js
- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
> fix(dropdown): corrects placeholder fonter color

- packages/site/pages/core/color.js
> site: Colors adjust

- packages/site/pages/components/viewtoggle.js
Add themeToggle to View Toggle examples now that they are theme aware.
> refactor(site): add themeToggle to View Toggle docs

- packages/site/pages/components/dropdown.js
> feat(site): add example to set dropdown with button

- packages/icon/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/icon/src/react/index.js
> fix(icon): restore svg coloring

- packages/button/src/css/index.js
- packages/button/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
related to:
https://pluralsight.slack.com/archives/C70HPSJPP/p1581032478122300
> fix(button): foreground visible on primary disabled state

- packages/link/src/css/index.js
- packages/link/src/react/index.js
> fix(link): className for featureFlags

- packages/banner/package.json
- packages/banner/src/css/index.js
- packages/banner/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/breadcrumb/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/button/src/css/index.js
- packages/button/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/emptystate/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/errors/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/layout/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/row/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/searchinput/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- New focus state across buttons (using box-shadow)
- Give all buttons a little push transition down on the active state
- Add hover, active, focus states for Primary button specific to light theme
- Make secondary button hover/active state more evident on light theme
- Make secondary button states for hover/active/focus consistent across themes
- Update styling of stroke button for better contrast on light and dark themes
> refactor(button): update button colors and interactions for states & themes

- packages/site/pages/components/code.js
- packages/site/pages/core/typography.js
> fix(site): remove encoded_closed_quotes

- packages/button/src/react/index.js
- packages/link/src/react/index.js
- packages/viewtoggle/src/react/index.js
Keeping linting errors in Travis on my branches  for files i'm not touching so I'm fixing the latest one.
> fix: removes conditional uses of useRef

- packages/site/pages/config.js
- packages/site/pages/core/build.js
- packages/site/pages/install.js
- packages/site/src/ui/side-nav.js
resolves #901 
resolves #894 
@danethurber & @jaketrent  let me know if build shows up under core links. Got a weird bug.
> feat(site): update build docs with SSR and peer dep setup info

- packages/tab/src/react/list.js
> fix(tab): fixes left arrow responsive bug

- packages/core/css/colors.module.css
> Fix bleutrals in CSS core

- packages/core/css/colors.module.css
- packages/core/js/colors.js
- packages/site/pages/components/code.js
- packages/site/pages/core/color.js
- Adding two code colors
- Documenting all colors
- Run site
> Update code colors

- package-lock.json
- packages/core/js/type.js
- packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/emptystate/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/layout/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/text/src/css/index.js
- packages/text/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
> fix(core): letter spacing values

- packages/site/pages/components/icon.js
Also made the icons 24x24.
Closes #951
> docs(site): fix layout issue with common icon set in Safari

- packages/avatar/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/breadcrumb/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/button/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/core/js/colors.js
- packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/note/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/row/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/searchinput/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/site/pages/core/color.js
> site: add utility colors

- packages/build/css/__specs__/glamor-to.css.spec.js
- packages/build/css/glamor-to-css.js
see https://github.com/pluralsight/design-system/pull/957
> fix(build): support building selectors as functions with glamor

- packages/site/pages/core/motion.js
> Fix opacity in site

- packages/circularprogress/src/index.d.ts
@jhewlett let me know what you think. i was attempting to make the component typings simpler to read and replicate. i had some patterns that i've been using on another project that i wanted to run by you
> CircularProgress: typing updates

- packages/site/pages/design-assets.js
> fix(site): figma links for design assets

- packages/table/src/react/__specs__/index.spec.js
- packages/table/src/react/index.js
Related: #934 -- resolves only one of the issues mentioned in the GH issue.
> table: add sort event to sort handler

- packages/textinput/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/textinput/src/react/__stories__/index.story.js
- packages/textinput/src/react/index.js
- Resolves #940
- Shouldn't dupe className
> textinput: apply className to label only

- packages/radio/src/css/index.js
- packages/radio/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/radio/src/react/__stories__/index.story.js
- packages/radio/src/react/group.js
- packages/site/pages/components/radio.js
Resolves #848
- Match other component labelling
- Tests, storybook, ref site
> Add labels to radio.group

- packages/dialog/src/css/index.js
- packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/dialog/src/react/__stories__/index.story.js
> fix(dialog): remove focus ring

- package-lock.json
- packages/actionmenu/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/position/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/position/src/react/__stories__/index.story.js
- packages/position/src/react/index.js
> fix(position): no longer clones child styles onto tooltip

- packages/note/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/note/src/react/__stories__/index.story.js
- packages/note/src/react/index.js
> feat(note): releases action limit

- packages/site/pages/components/position-portal-example.js
- packages/site/pages/components/position.js
From Matthew Ma in Slack
Hi, I am wondering if the portal option is still useful. It looks to me that Position will render to its own portal by default.
...Yep
> Clean position doc

- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/radio/src/css/index.js
- packages/radio/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/radio/src/react/__specs__/index.spec.js
- packages/radio/src/react/__stories__/index.story.js
- packages/radio/src/react/button.js
- packages/radio/src/react/group.js
radio PR didn't bump to new major rolling back
> fix(radio): rollback radio

- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/radio/src/css/index.js
- packages/radio/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/radio/src/react/__specs__/index.spec.js
- packages/radio/src/react/__stories__/index.story.js
- packages/radio/src/react/button.js
- packages/radio/src/react/group.js
BREAKING CHANGE: Radio.Group now require name prop and onSelect renamed onChange, Radio.button checked, onFocus, and onKeydown props removed
> feat(radio): new component api and usage of context

- packages/table/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/table/src/react/index.js
> fix(table): add aria-sort for a11y

- packages/site/pages/components/table.js
- packages/table/src/css/index.js
- packages/table/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/table/src/react/__specs__/index.spec.js
- packages/table/src/react/index.js
> fix(table): update column header click event arg order and aria-sort

- packages/carousel/src/react/context.js
- packages/carousel/src/react/control.js
- packages/carousel/src/react/index.js
> feat(carousel): fixes transitioning of carousel

- packages/site/pages/components/table.js
- packages/table/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/table/src/react/index.js
Resolves https://pluralsight.slack.com/archives/C70HPSJPP/p1593792781288200
> fix(table): doubled up click handler nulling sort

- packages/position/src/js/index.js
- packages/site/pages/components/position.js
> fix(position): add yOffset to clipAdjust

- packages/navbar/package.json
- packages/navbrand/package.json
- packages/navitem/package.json
- packages/navuser/package.json
> Fix Nav Peer Deps

- packages/navitem/src/css/index.js
- packages/navitem/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/navitem/src/react/common.js
- packages/navitem/src/react/horz.js
- packages/navitem/src/react/index.js
- packages/navitem/src/react/vert.js
- Vert NavItem was too tall
- Horz NavItem was too short
- Both should come out to 56px in order to fit in and align vertically inside NavBar
> Decrease vertical NavItem height

- packages/scrollable/package-lock.json
- packages/scrollable/package.json
- packages/scrollable/src/react/index.js
- Build failing because Image is not defined https://teamcity.vnerd.com/viewLog.html?buildId=861251&buildTypeId=Platform_DesignSystem_DesignSystemBuildDeploy&tab=buildLog
- Found another eslint error in the usage of the Elvis operator
> Fix Scrollable for Build

- packages/site/pages/components/table.js
> Site typo 2

- packages/appframe/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/navbar/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/navitem/src/css/index.js
- packages/navitem/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/navitem/src/react/common.js
- packages/navitem/src/react/index.js
More to get it in line with figma.  Zoinks!
> More navitem vert adjustments

- packages/navitem/src/css/index.js
- packages/navitem/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
After pow wow with Brian. Figma adjustments.
> Redo NavItem Vert Spacing

- packages/dialog/package.json
- packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/dialog/src/react/__stories__/index.story.js
- packages/dialog/src/react/index.js
Meant to accomplish the same thing as:
https://github.com/pluralsight/design-system/pull/1123
Resolves: #1127
> Dialog: stylesFor __content

- docs/package.json
- docs/src/components/layouts/default.tsx
- docs/src/components/mdx-components.tsx
- docs/src/pages/index.mdx
> Use DS components in MDXProvider

- docs/src/components/side-nav/index.tsx
- docs/src/components/spacing/example.module.css
- docs/src/components/spacing/example.tsx
- docs/src/components/spacing/index.ts
- docs/src/components/spacing/individual-spacing.tsx
- docs/src/components/spacing/spacing-increments.tsx
- docs/src/pages/core/spacing.mdx
> Spacing page

- docs/package-lock.json
- docs/package.json
- docs/src/components/color/color-categories.tsx
- docs/tsconfig.json
- docs/typings/css-module.d.ts
- docs/typings/postcss.d.ts
- docs/typings/undefined.d.ts
- package-lock.json
- package.json
> Fix a bunch o TS errors

- docs/package.json
- docs/src/components/frame/frame.tsx
- Load site
- Click theme toggle
- Refresh and/or go to other pages, see that theme is kept
> feat(docs): persist theme selection

- docs/src/pages/components/avatar.mdx
- docs/src/pages/core/color.mdx
- docs/src/pages/core/motion.mdx
- docs/src/pages/core/spacing.mdx
- docs/src/pages/core/typography.mdx
let's show off that sweet syntax highlighting!!
> feat(docs): add missing languages to codeblocks

- docs/src/components/code-block/actions.tsx
- docs/src/hooks/use-previous.ts
> fix(docs): reset copy button after timeout

- docs/src/components/code-block/package-map.ts
- docs/src/components/mdx/index.tsx
- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/circularprogress.mdx
> Circ prog docs

- docs/src/pages/components/circularprogress.mdx
> style(docs): convert circprog styles to jsx in example

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/datawell.mdx
> feat(docs): datawell pg

- docs/src/components/color/color-categories.module.css
- docs/src/components/color/color-categories.tsx
> fix(docs): color category labels themeable

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/typeahead.mdx
> typeahead docs

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/errors.mdx
> feat(docs): error pages

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/theme.mdx
> add theme docs

- docs/src/components/frame/aside.module.css
> fix(docs): let the sidenav scroll

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/tab.mdx
> feat(docs): tab pg

- docs/src/components/side-nav/index.tsx
- docs/src/global/style.css
- docs/src/pages/components/nav.mdx
> feat(docs): nav pg

- docs/src/pages/components/breadcrumb.mdx
> feat(docs): breadcrumb page

- docs/src/components/carousel.tsx
- docs/src/components/guidelines/guideline.module.css
- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/carousel.mdx
> feat(docs): carousel page

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/starrating.mdx
> feat(docs): starrating page

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/linearprogress.mdx
- docs/src/pages/components/link.mdx
> docs: linearprogress and link

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/screenreaderonly.mdx
> screen reader docs

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/scrollable.mdx
> scrollable docs

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/table.mdx
> table docs

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/text-headings.mdx
- docs/src/pages/components/text-lists.mdx
- docs/src/pages/components/text-paragraph.mdx
> feat(docs): text docs

- docs/src/components/layouts/default.tsx
> feat(docs): add meta title

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/drawer.mdx
> feat(docs): drawer page

- docs/src/components/mdx/index.module.css
- docs/src/components/mdx/index.tsx
- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/layout-aside.mdx
- docs/src/pages/components/layout-column.mdx
- docs/src/pages/components/layout-page-heading.mdx
- docs/src/pages/components/layout-page-width.mdx
> layout docs

- docs/src/components/code-block/package-map.ts
- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/featureflags.mdx
> add featureflag docs

- docs/src/components/side-nav/index.tsx
- docs/src/pages/components/appframe.mdx
> add appframe docs

- docs/src/components/component.ts
- docs/src/components/mdx/index.tsx
- docs/src/pages/components/dialog.mdx
- docs/src/pages/components/tooltip.mdx
Went down the mdx-js/react road, but figured it wasn't worth it at the moment. Probably possible, but I wasn't patient enough.
> Fix dialog intro

- docs/src/pages/components/actionmenu.mdx
- docs/src/pages/components/avatar.mdx
- docs/src/pages/components/badge.mdx
- docs/src/pages/components/banner.mdx
- docs/src/pages/components/breadcrumb.mdx
- docs/src/pages/components/button.mdx
- docs/src/pages/components/card.mdx
- docs/src/pages/components/carousel.mdx
- docs/src/pages/components/circularprogress.mdx
- docs/src/pages/components/datawell.mdx
- docs/src/pages/components/datepicker.mdx
- docs/src/pages/components/dialog.mdx
- docs/src/pages/components/errors.mdx
- docs/src/pages/components/nav.mdx
- docs/src/pages/components/starrating.mdx
- docs/src/pages/components/switch.mdx
- docs/src/pages/components/tab.mdx
- docs/src/pages/components/textinput.mdx
> fix(docs): sentence casing on page titles

- packages/actionmenu/package.json
- packages/viewtoggle/package.json
- yarn.lock
> Rm glamorous

- docs/src/components/frame/frame.tsx
> fix(docs): fix meta margin for guides pages

- docs/src/components/frame/frame.tsx
> feat(docs): respect os theme preference

- docs/gatsby-ssr.js
- docs/src/components/frame/frame.tsx
> refactor(docs): use ssr for font

- docs/src/components/intro.module.css
- docs/src/content/core/voice.mdx
- Adjustments to the copy on the voice & tone page
- Reduced the font weight on the intro text.
> refactor(docs): adjustments to voice & tone copy

- docs/src/components/box.module.css
- docs/src/components/box.tsx
- docs/src/components/typography/font-family.module.css
- docs/src/components/typography/font-family.tsx
- docs/src/components/typography/font-size.module.css
- docs/src/components/typography/font-size.tsx
- docs/src/components/typography/font-weight.module.css
- docs/src/components/typography/font-weight.tsx
- docs/src/components/typography/line-height.module.css
- docs/src/components/typography/line-height.tsx
- docs/src/components/typography/monospace-font.module.css
- docs/src/components/typography/monospace-font.tsx
> Daaaaark mode in typography

- docs/gatsby-config.js
- docs/package.json
- docs/src/components/side-nav/index.tsx
- yarn.lock
> docs: adds docusearch

- packages/table/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- packages/table/src/react/index.js
Looks like destructuring modified props and the source of the prop was unclear and thus misused in the code.
> fix(table): highlight color on sorted column header

- docs/src/components/frame/frame.module.css
> fix(docs): rm min-width constraint from frame to rm x scroll

- docs/src/components/code-block/actions.tsx
> feat(docs): supply deps to new codesandboxes

- docs/src/components/side-nav/index.module.css
- docs/src/components/side-nav/index.tsx
> refactor(docs): give side nav custom scroller

- docs/src/content/components/layout-aside.mdx
- docs/src/content/components/layout-column.mdx
- docs/src/content/components/layout-page-width.mdx
> fix(docs): single line commits to fix transform in preview

- docs/src/components/mdx/index.module.css
- docs/src/components/mdx/index.tsx
> feat(docs): linked headings in mdx

- docs/src/components/box.module.css
- docs/src/components/box.tsx
- docs/src/components/code-block/styles.module.css
- docs/src/components/frame/aside.module.css
- docs/src/components/frame/aside.tsx
- docs/src/components/frame/frame.module.css
- docs/src/components/frame/header.module.css
- docs/src/components/frame/header.tsx
- docs/src/components/guidelines/guideline.module.css
- docs/src/components/guidelines/guideline.tsx
- docs/src/components/intro.module.css
- docs/src/components/intro.tsx
- docs/src/components/mdx/index.module.css
- docs/src/components/mdx/index.tsx
- docs/src/components/motion/speeds.module.css
- docs/src/components/typography/font-size.module.css
- docs/src/components/typography/font-size.tsx
- docs/src/components/typography/font-weight.module.css
- docs/src/components/typography/font-weight.tsx
- docs/src/components/typography/line-height.module.css
- docs/src/components/typography/monospace-font.module.css
- docs/src/components/typography/monospace-font.tsx
- docs/src/components/usage.module.css
- docs/src/components/usage.tsx
- docs/src/components/voice/index.module.css
- docs/src/components/voice/index.tsx
- yarn.lock
- Should help us avoid doing .dark and .light classes on low level components for basic things
- Still exists where it doesn't make sense to create app-level variables
- Relies on css vars being available. Chosee frame.tsx to provide it since it also has the Theme.Provider
> Move theming to app level

- packages/util/color.js
- packages/util/prop-defs.js
- packages/util/props.js
- packages/util/string.js
> fix(util): import references wrong dist folder

- packages/position/src/react/index.js
i should have just looked at the eslint warnings....spent time debugging when the linter was telling me exactly what was wrong 🤦
> fix(position): update on ref change

- docs/src/components/side-nav/index.module.css
- docs/src/components/side-nav/index.tsx
> Fix scrollbar horz alignment

- docs/src/components/table-of-contents.module.css
> Resolve vnerd styles diff

- docs/src/components/frame/aside.tsx
- docs/src/components/side-nav/index.tsx
Resolves #1320
- feat(docs): highlight active sidenav link
- feat(docs): open sidenav group containing active link
- feat(docs): persist sidenav group toggling
- fix(docs): restore the scroll restore, broken by scrollable
- refactor(docs): rename vars for clarity
> Persist sidenav group toggling

- packages/dialog/src/react/index.tsx
> fix(dialog): bug with stylesFor lookup

- docs/src/components/mdx/index.tsx
> fix(docs): export mdx components for usage on HomePage

- packages/util/src/use-match-media.ts
> fix(util): update hook that fails during SSR

- packages/dropdown/src/css/index.ts
- packages/dropdown/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/dropdown/src/react/__stories__/index.story.tsx
> fix(dropdown): set max height

- docs/src/components/frame/frame.tsx
Not 100% this will fix it, but it does seem to address the symptom of multiple session cookies.
> fix(docs): set one cookie for all paths and time

- docs/src/content/components/checkbox.mdx
- docs/src/content/components/circularprogress.mdx
- docs/src/content/components/drawer.mdx
- docs/src/content/components/linearprogress.mdx
- docs/src/content/components/radio.mdx
examples only support single-line imports atm
> Fix docs imports

- docs/src/components/frame/frame.tsx
Prod is acting differently than local, so I need to figure out why. This adds temp loggin.
> fix(docs): debug log theme cookie

- docs/src/components/frame/frame.tsx
initialTheme looks right but UI does not.  
Move logging further down the line to see how the className actually gets applied.
> fix(docs): more theme debug logging

- docs/src/content/components/card.mdx
> fix(docs): one line import card

- docs/src/components/code-block/code-block.tsx
- docs/src/components/code-block/styles.module.css
- docs/src/content/components/nav.mdx
> fix(docs): fix themeName override

- docs/gatsby-ssr.js
- docs/src/components/frame/frame.module.css
- docs/src/components/frame/frame.tsx
Double checked with Sweeting.  He sees this is as a ux-neutral/lil-positive change, so we're good on that front.
> Default docs theme to dark

- docs/src/content/core/voice.mdx
> fix(docs): voice and tone page layout/scroll update

- docs/src/components/code-block/styles.module.css
- docs/src/components/table-of-contents.module.css
- docs/src/components/types/prop.module.css
- docs/src/components/typography/line-height.module.css
- docs/src/content/index.module.css
> fix(docs): update data-psds-theme attr for missed styles

- docs/src/content/examples/position.mdx
> fix(docs): cleanup positions example

- packages/button/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/button/src/react/__stories__/index.story.tsx
missed story file.  cleaning up
> TS Convert Button Story

- packages/banner/src/temp-psds-icon.d.ts
- packages/carousel/src/react/__stories__/index.story.tsx
- packages/carousel/src/temp-psds-position.d.ts
ignored when missing. now the TS conversion for these is done, reference the types
> stop ignore internal component types

- packages/tab/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/tab/src/react/__stories__/index.story.tsx
- packages/tab/src/react/list.tsx
As in cases where listitems might be conditionally shown and there are
nulls in the list
Resolves: #1350
> fix tab null listitem active problem

- packages/datepicker/src/react/__specs__/index.spec.tsx
- packages/datepicker/src/react/index.tsx
Well this is embarrassing.  Somehow got removed in TS conversion.  
Wrongly removed in 3751cee52e
> Fix broken calendar on datepicker

- docs/src/content/components/form-controls.module.css
- docs/src/content/components/form-controls.tsx
- docs/src/content/components/form.mdx
Resolves: #1443
Resolves: #1444
> a couple form docs fixes

- packages/card/src/react/__specs__/storyshots.spec.tsx
- packages/carousel/src/react/__specs__/storyshots.spec.tsx
- packages/row/src/react/__specs__/storyshots.spec.tsx
- packages/tab/src/react/__specs__/storyshots.spec.tsx
> rm ts-ignore for storyshots createnodemock

- docs/src/content/components/textarea.mdx
- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/textarea/src/css/index.ts
- packages/textarea/src/index.ts
- packages/textarea/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/textarea/src/react/__stories__/index.story.tsx
- packages/textarea/src/react/index.tsx
- packages/textarea/src/vars/index.ts
- packages/textarea/vars.js
> textarea subtle appearance

- docs/src/components/code-block/styles.module.css
- docs/src/components/frame/frame.module.css
For those things that don't natively respond to Theme.Provider. We had bg. Now we have fg.
> docs default fg colors

- packages/text/react.js
And I actually found a meaningful change to make :)
> bump text version

- packages/dropdown/src/react/__specs__/index.spec.tsx
- packages/dropdown/src/react/input.tsx
- packages/dropdown/src/react/item.tsx
> allow falsy values to be selected in dropdown

- docs/src/content/components/icon-common-set.tsx
- docs/src/content/components/icon.mdx
> fix icons invisible in docs dark theme

- packages/core/css/index.css
- packages/core/css/layers.module.css
- packages/core/js/index.ts
- packages/core/js/layers.ts
- packages/core/js/layout.ts
Combined from appframe and prism codebases:
// appframe
/* DONE content: 0, */
/* DONE sidenav: 930, */
/* DONE topnav: 950, */
/* DONE skipBanner: 1600 */
//prism
/* DONE main: 0, */
/* RM, moved away from in design - footerMobile: 930, */
/* RM, not used in new appframe - sidenavMobile: 940, */
/* DONE topnav: 950, */
/* RM, not used in new appframe - sidenavDesktop: 980, */
/* RM, moved away from in design - footerDesktop: 990, */
/* DONE dropdown: 1000, */
/* RM, unused cookieBanner: 1002, */
/* RM, unused dropdownArrow: 1002, */
/* RM, unused in appframe - searchMobile: 1010, */
/* RM, unused searchOverlay: 1500, */
/* DONE skipBanner: 1600 */
> layers into core

- packages/button/src/css/index.ts
- packages/button/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/button/src/react/__stories__/index.story.tsx
- packages/button/src/react/index.tsx
- packages/button/src/vars/index.ts
> full width to button

- packages/navitem/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/navitem/src/react/__stories__/index.story.tsx
- packages/navitem/src/react/common.tsx
- packages/navitem/src/react/context.tsx
- packages/navitem/src/react/index.tsx
> fix(navitem): pass unspecified props to button

- packages/table/src/css/index.ts
- packages/table/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/table/src/react/index.tsx
I'm not 100% I fully understand how wide of a background removal we're asking for here, so I took my best guess.  Please verify.  I left a number of background styles because I think we still want them (eg, sticky headers and hover states).
Resolves: #1546
> remove table background

- docs/src/components/side-nav/index.tsx
- docs/src/content/components/table.mdx
- fix(docs): safer docsearch call to fix local
- fix(docs): adjust table pagination example cursor code
Thanks, @culli, for the fix code.  Looks great.
> fix table pagination doc

- packages/card/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/card/src/react/index.tsx
- packages/carousel/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
> fix card actionBarVisible

- packages/datepicker/src/react/calendar.tsx
- packages/datepicker/src/react/index.tsx
- Remove calendar internal state
- Update input fields based on parent state change
Resolves: #1544
> fix datepicker loop

- packages/navbar/src/react/__stories__/index.story.tsx
- packages/navbar/src/react/index.tsx
- packages/navitem/package.json
- packages/navitem/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/navitem/src/react/__specs__/index.spec.tsx
- packages/navitem/src/react/__stories__/index.story.tsx
- packages/navitem/src/react/common.tsx
- packages/navitem/src/react/context.tsx
- packages/navitem/src/react/index.tsx
> fix navitem forwardref

- docs/src/content/guides/developmentworkflow.mdx
> update core usage dev docs

- packages/dropdown/src/react/__specs__/index.spec.tsx
Seems to work. What am I missing?
> test(dropdown): add disabled menu case

- packages/normalize/css/index.css
- packages/text/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/text/src/react/__stories__/p.story.tsx
> fix italics for chrome

- docs/src/content/components/button.mdx
Resolves #1574
See continuing convo with Andy at: https://pluralsight.slack.com/archives/C70HPSJPP/p1611351088007400
> clarify button loading in docs

- packages/dialog/src/css/index.ts
- packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
Matched flat Button style. But didn't make Button a dependency. Was going for a smaller package size. Right choice?
> fix(dialog) increase close button color contrast for a11y

- packages/actionmenu/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/actionmenu/src/react/__specs__/index.spec.tsx
- packages/actionmenu/src/react/item.tsx
- packages/carousel/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
> test(actionmenu): add getByRole tests

- packages/util/src/use-close-on-document-events.ts
> fix(util): was losing ref on closest check

- packages/carousel/src/react/index.tsx
> fix(carousel): remove flash when used with cards

- docs/src/content/components/verticaltabs.mdx
> refactor(docs): remove icon prop from VerticalTabs.Tier2.Header

- docs/src/content/components/nav.mdx
> update style override docs for navitem

- packages/screenreaderonly/.npmignore
> screenreaderonly npmignore

- packages/tagsinput/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/tagsinput/src/react/index.tsx
> fix(tagsinput): remove unintended empty dom for missing labels

- packages/navcookiebanner/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/navcookiebanner/src/react/index.tsx
this is a quick ask from amber. i guess this is the correct approach. i have a similar card in prism that i will also tackle shortly
> fix(navcookiebanner): change aria-label on close icon

- docs/src/content/components/text-label.mdx
- packages/normalize/css/index.css
- packages/text/src/css/index.ts
- packages/text/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/text/src/react/__stories__/label.story.tsx
- packages/text/src/react/label.tsx
> text: add mono to label

- packages/datepicker/package.json
> build(datepicker): remove unused react-dates dependency

- packages/datepicker/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/dropdown/src/css/index.ts
- packages/typeahead/src/css/index.ts
> fix(typeahead): add z-index to typeahead dropdown and update dropdown

- docs/src/content/core/typography.mdx
> refactor(docs): remove domain restriction comment

- packages/avatar/src/react/__specs__/index.spec.tsx
- packages/button/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/button/src/react/__specs__/index.spec.tsx
- packages/button/src/react/__stories__/index.story.tsx
> refactor(button): convert stories to csf. add jest-axe tests

- docs/src/content/components/searchinput.mdx
resolves  #1703 
* totally splitting up typeahead since I can't get conflicts to resolve and it to still work since esm update
> docs: correct implementation info

- packages/datepicker/src/react/text-input-field.tsx
- packages/field/src/index.ts
- packages/field/src/react/field.tsx
- packages/field/src/react/index.ts
Prework for #1706. Need to be able to forwardRef to field component.
> refactor(field): update type exports and forwardRef impl

- packages/screenreaderonly/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/screenreaderonly/src/react/__specs__/index.spec.tsx
- packages/screenreaderonly/src/react/__stories__/index.story.tsx
- packages/screenreaderonly/src/react/index.tsx
> ScreenReaderOnly: use primates and convert stories to CSF

- packages/verticaltabs/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/verticaltabs/src/react/__specs__/index.spec.tsx
- packages/verticaltabs/src/react/__stories__/examples.story.tsx
- packages/verticaltabs/src/react/__stories__/index.story.tsx
> refactor(verticaltabs): convert stories to csf

- packages/viewtoggle/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/viewtoggle/src/react/__specs__/index.spec.tsx
- packages/viewtoggle/src/react/index.tsx
> fix(viewtoggle): update aria attribute

- LICENSE
RE: https://pluralsight.slack.com/archives/C5CMEKH5Z/p1620320610191900
Add copyright year and company name to LICENSE
> refactor: add copyright year and company name to license

- docs/src/content/components/position.mdx
> refactor(docs): add forwardref note to position

- packages/dropdown/src/js/index.ts
- packages/dropdown/src/react/menu.tsx
Resolves: #1741
We be scrollin'...!
> fix dropdown in-menu scroll

- docs/src/content/components/position.mdx
> feat(docs): add position component style prop note

- packages/dropdown/src/react/__specs__/index.spec.tsx
- packages/dropdown/src/react/item.tsx
- packages/menu/src/react/item.tsx
- packages/select/src/react/__specs__/index.spec.tsx
Forgot about enter doing select. Added test to cover that
https://pluralsight.slack.com/archives/C70HPSJPP/p1621604860015000?thread_ts=1621363066.003300&cid=C70HPSJPP
> fix: enter selects and closes menu

- packages/select/src/react/useListbox.ts
- The problem is the closeMenu function in useListbox file always focuses on the button after initial render. Expected behavior: The button should be focused only if the menu is open.
> select: focus trap happening in useListbox

- packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/drawer/src/react/__specs__/index.spec.tsx
- packages/drawer/src/react/__stories__/index.story.tsx
- packages/emptystate/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/emptystate/src/react/__specs__/index.spec.tsx
- packages/emptystate/src/react/__stories__/index.story.tsx
- packages/errors/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/errors/src/react/__specs__/index.spec.tsx
- packages/errors/src/react/__stories__/index.story.tsx
Man, no wonder Dane went to PS@PS. These are boring.
> CSF fer a D and some Es

- packages/viewtoggle/src/css/index.ts
- packages/viewtoggle/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/viewtoggle/src/react/index.tsx
- packages/viewtoggle/src/vars/index.ts
BREAKING CHANGE: increase vertical height from 24px to 32px
> refactor(viewtoggle): larger text style

- packages/dropdown/src/js/index.ts
> fix(dropdown): remove undesirable css type from dropdown.item

- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/switch/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/switch/src/react/__specs__/index.spec.tsx
- packages/switch/src/react/__stories__/index.story.tsx
- packages/switch/src/react/index.tsx
> switch: make focusable

- packages/appframe/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/verticaltabs/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/verticaltabs/src/react/group.tsx
- packages/verticaltabs/src/react/item.tsx
> fix(verticaltabs): update aria roles

- packages/appframe/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/verticaltabs/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/verticaltabs/src/react/item.tsx
> fix(verticaltabs): disallow focusing collapsed tier2 headers

- docs/src/content/components/menu.mdx
- packages/menu/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/menu/src/react/__specs__/index.spec.tsx
- packages/menu/src/react/__stories__/index.story.tsx
- packages/menu/src/react/item.tsx
> fix(menu): only use aria-selected on options for role=listbox

- docs/src/content/components/datepicker.mdx
- packages/datepicker/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/datepicker/src/react/__stories__/index.story.tsx
- feat(docs): add value prop and example to datepicker
- test(datepicker): remove cruft that isnt focus on value story
> datepicker docs for value

- docs/src/content/guides/developmentworkflow.mdx
> feat(docs): add section on overriding css

- docs/src/content/components/position.mdx
- packages/position/src/js/index.ts
- packages/position/src/react/__stories__/index.story.tsx
- packages/position/src/react/index.tsx
> feat(tooltip): allowOffscreen rendering

- packages/radio/src/css/index.ts
- packages/radio/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/radio/src/react/__stories__/index.story.tsx
- packages/radio/src/react/button.tsx
> Disable styles for Radio.Button

- docs/src/components/code-block/actions.tsx
- docs/src/content/core/color.mdx
- docs/src/content/core/motion.mdx
- docs/src/content/core/spacing.mdx
- docs/src/content/core/typography.mdx
- docs/src/content/guides/developmentworkflow.mdx
> fix(docs): dashify css var references

- docs/src/content/components/button.mdx
- docs/src/content/components/checkbox.mdx
- docs/src/content/components/datepicker.mdx
- docs/src/content/components/dropdown.mdx
- docs/src/content/components/field.mdx
- docs/src/content/components/form.mdx
- docs/src/content/components/multiselect.mdx
- docs/src/content/components/radio.mdx
- docs/src/content/components/searchinput.mdx
- docs/src/content/components/switch.mdx
- docs/src/content/components/tagsinput.mdx
- docs/src/content/components/textarea.mdx
- docs/src/content/components/textinput.mdx
- docs/src/content/components/typeahead.mdx
- docs/src/content/components/viewtoggle.mdx
Added a11y sections, Figma links, and reorganized contents of docs pages in the Inputs nav sections.
> Docs a11y - Inputs pages

- packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/dialog/src/react/__stories__/index.story.tsx
- packages/dialog/src/react/index.tsx
- make close button the last focusable element in the dialog
- add stories for setting focus on a heading and a heading hidden from screenreader
Paired w/ @danethurber 
Closes #1989
> Dialog: focus

- packages/table/package.json
- packages/table/src/css/index.css
- packages/table/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/table/src/react/__stories__/index.story.tsx
- yarn.lock
Make it easier to override hover styles by killing universal selector
> fix(table): remove unecessarry universal selector

- packages/actionmenu/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/carousel/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/menu/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/multiselect/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- packages/navbar/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/navitem/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/navuser/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/note/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/position/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/position/src/react/index.tsx
- packages/select/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
- packages/typeahead/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- yarn.lock
https://pluralsight.slack.com/archives/C70HPSJPP/p1632416018084000
> fix(position): fix scroll jank caused by the position  component

- Dockerfile.docs
Updates node version in Dockerfile.docs to prevent docs build from failing.
> fix: update Dockerfile.docs node version

- .gitlab-ci.yml
- Dockerfile.docs
> fix: update .gitlab-ci.yml node img to match Dockerfile.docs

- .gitlab-ci.yml
- Dockerfile.docs
- docs/package.json
- package.json
Gitlab CI failing due to python missing. Updates command based on docker recommendations.
> fix: update dockerfile.docs run python command

- packages/icon/src/react/icons/index.ts
- packages/icon/src/react/icons/message.ts
closes #2031 
MenuCloseIcon naming does not match design files.
* Deprecates MenuCloseIcon
* Adds MenuArrowRightIcon & MenuArrowLeftIcon
*
> feat(icon): add MenuArrow${Right,Left}Icon

- docs/CHANGELOG.md
- docs/package.json
- packages/actionmenu/package.json
- packages/dropdown/package.json
contributes to #2025 
GH pages publish is failing due to a bad dep tree with PSDS components
Updates some of the deps to be less strict.
> ci: update package deps that are erroring for bad tree

- .yarnrc
Yarn is using a very very old version.
Updates to use Yarn classic as step 1 to move to Yarn berry
> build: use Yarn classic

- docs/src/components/voice/index.tsx
Quote block missing styles
Quote styles present
Fixes #2019
> fix(docs): closes #2019 - fix overwritten className prop

- package.json
- yarn.lock
> build(deps): Upgrade link-parent-bin to 2.0.0

- packages/form/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
> test(form): update form snapshot after switch update

- yarn.lock
using version 2.0.0, flagged by Snyk
using version 2.0.1, containing fix for identified issue
> deps: update nth-check via css-select

- docs/package.json
- docs/yarn.lock
many dependencies were listed as prod deps
Since the deps are not needed in prod, moved all to dev
> deps: move all docs deps to dev

- packages/build/package.json
Security issues raised due to dependencies in the 'build' package.  
Dependencies now listed as devDependencies, since they are not used in a production environment, but only when building packages.  This will alleviate security concerns.
> deps: move all 'build' package deps to dev

- README.md
> Updates for maintenance mode
