pluralsight/classic-design-system

packages/row/src/react/index.js
A few spacing and line-height adjustment to match design.
There was a typo (missing .core.) that was causing title line-height not work.
Also, suggesting flex box center VS. padding for `words`, so that the text is centered regardless of string length or metadata inclusion.
=> refactor(row): spacing and line-height adjustment

packages/tab/src/react/list.js
When you try to change the active tab from outside the `Tab.List`, by changing the active props on one of the children it doesn't work, but if you are changing the tabs by clicking on one of the tabs it works great.
Because we are using a state `activeIndex` to actually define the `active` prop passed to the children and this state is only being set on mount and on ListItem click, once you try to change the active tab by changing the `<Tab.ListItem active={true} />`, it won't change the state.
We need to implement `componentWillReceiveProps` and set activeIndex state when necessary.
I found this problem because I'm using the route the user is on to define with tab should be active, but if you trigger a goBack action on history browser, it won't re-mount the component, so it needs to …
=> fix(tab): set activeIndex state on children props update

packages/link/react.d.ts
- This change adds typescript typings for the React Link component
- I used a union type for two `appearance` values. I'm pretty new to typescript, so I'm not sure if that's a good/bad pattern. The downside to it is that if an appearance style is added, it will need to be updated in the type definition. Upside is compile time assurance that the value is correct.
- The only way I really know to verify this is to pull it into a typescript/react app and see that it compiles. I've done this on the project I'm using the design system on and it seems to be working.
=> link: add typescript typings for react component

packages/row/src/react/index.js
In certain cases, the row image and actions are shrinking when the Words
section runs out of space (see attached screenshot). This fix makes sure the Words section will collapse all the way to zero before the other flex items start collapsing.
We've spent a while trying to reproduce this exact behavior and have not found a consistent way to do so outside our specific use case. We tested to make sure the fix did not change any of the examples in the design system site.
=> Row: prevent row image from shrinking

packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/drawer/src/react/index.js, packages/drawer/stories/index.js
Adds ability to start the drawer open. Currently only planed for use in examples in the DS site.
Add the `startOpen` prop to the drawer component and verify it loads open and is able to be closed.
=> feat(drawer): allow starting open

packages/site/next.config.js, packages/site/package.json, packages/site/pages/components/drawer.js, packages/site/pages/components/theme.js, packages/site/src/ui/side-nav.js
Adds documentation page for `drawer` component to site
- Load site and nav to the Drawer page
=> feat(site): add drawer page

packages/badge/css.js, packages/badge/index.js, packages/badge/src/css/index.js, packages/badge/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/badge/src/react/index.js, packages/badge/src/vars/index.js, packages/badge/vars.js
Proof of concept for extracting css (and exported vars) from a design system component (badge, as the simple example).  It works in storybook and local reference site.  Feedback welcome.  
- Is it worth it?  Good investment?  
- Are there better ways to do a similar thing?
- A potential way to allow sharing css between diff side-by-side or future component techs
- Or building/publishing raw css
- Plain JavaScript, compatible with that, at least
- JS could be built to JSON, converted to any other formats, including *.css
=> badge: extract css and vars modules

packages/button/src/react/index.js
- Allow overriding the tabIndex of a button. This is useful when we place buttons inside links (like react-router's `Link` component) and want to prevent the button from being tabbed to.
- Create a button that has `tabIndex="-1"` and verify it cannot be tabbed to.
=> button: Add tabIndex to attr whitelist

packages/drawer/src/react/collapsible.js
- If a drawer is opened and then closed, you are able to tab into the invisible content. That seems bad.
Fixing this in collapsible makes sure that styles are updated only after animations have completed.
- Add a focusable element inside a drawer
- Expand the drawer and verify that the element can be tabbed to
- Collapse the drawer and verify that the element can no longer be tabbed to
=> drawer: prevent tabbing into closed drawers

packages/avatar/CHANGELOG.md, packages/avatar/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/avatar/src/react/__specs__/utils.spec.js, packages/avatar/src/react/index.js, packages/avatar/src/react/styles.js, packages/avatar/src/react/utils.js, packages/avatar/src/vars/index.js, packages/avatar/stories/index.js
This PR implements the following:
- Change initials font-weight from `ExtraLight` to `Book`
- Adds a transparent image as default fallback on gravatar urls.
- Add `[?|&]d=https://cdn/transparent.gif` param at the end of gravatar urls.
```jsx
<Avatar src="https://secure.gravatar.com/..." name="Anakin Skywalker" />
```
When you pass a gravatar link that doesn't have a picture
Before             |  After
:-------------------------:|:-------------------------:
=> Avatar: Style changes and Gravatar friendly

.gitignore, .vscode/settings.json, packages/button/src/react/__specs__/index.spec.js, packages/button/src/react/index.js
- Fix: Disabled buttons don't get disabled if they have an href prop
- When an href prop is passed, the button is rendered using an anchor tag. Anchor tags ignore the disabled attribute.
- I implemented this by removing (without mutating) onClick from the whitelisted props only when disabled and href are both passed.
- Add a disabled prop to a Button that also has an href prop
=> Disabled button click fix

packages/tag/src/react/index.js
- Allows passing a node as children instead of just a string. Makes it easier to
control the way children are ellipsified.
- Resolves issue #188 
- Verify you can pass a node in as the children to a `tag` component
=> tag: change children propType from string to node

packages/avatar/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/avatar/src/react/index.js, packages/avatar/src/vars/index.js, packages/avatar/stories/index.js
Help remove color halo that bled out from behind loaded images.  Had to
change the gravatar fallback strategy to support this.  Otherwise, the
rule was that we always show initials in the case of gravatar images.
But we don't want this, because depending on the color combo, the halo
is visible.  Instead, now we fail gravatar images like any other.
Closes #191
=> fix(avatar): hide img or initials based on img load state

packages/button/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/button/src/react/index.js, packages/button/stories/index.js
In a spa we often wrap the button within a Link tag, and need a way to assign a role to the button. This pull-request adds `role` to the whitelist and allows it to be attached to the generated comp.
=> refactor(button): whitelist role for button

packages/site/pages/components/breadcrumb.js, packages/site/pages/core/typography.js
- fill in title: "Fix typos on site pages"
- label: bug
- Fixing two typos on the static site pages - one under 'Breadcrumb' and one under 'Typography'
- N/A
- N/A
=> Fix typos on site pages

packages/actionmenu/CHANGELOG.md, packages/actionmenu/package.json, packages/actionmenu/src/css/index.js, packages/actionmenu/src/react/index.js, packages/site/CHANGELOG.md, packages/site/package.json
- Allow passing custom icons to action menu items via an icon prop
- Needed custom social media icons for share menu
- Pass a custom icon component to an action menu item and verify it shows up
=> actionmenu: allow custom icons

packages/datepicker/src/js/index.js
This has been logging quite a bit in our tests and elsewhere. I'm assuming it's an oversight so submitting a quick PR -- if not let me know :)
=> datepicker: remove console.log statement from parseDate

packages/button/src/css/index.js
- site: fix tooltip flicker on hover [chrome]
- label: bug
- see #194 and an imperfect solution [in this first round pull request](https://github.com/pluralsight/design-system/pull/245)
- Round Two! 🥊 I spent some additional time looking into this bug after reviewing the excellent feedback from @jaketrent in the [original PR](https://github.com/pluralsight/design-system/pull/245).
- I noticed the tooltip flicker only occurred on webkit browsers, and only when the cursor moved across the boundary of the child `<span />` text element nested within the `<button />`. Applying a `pointer-events: none` style to that `<span />` prevented the `onMouseOut` callback from being fired for the parent `<button />` and eliminated the flicker! 
- See `Hover me` example under …
=> fix(site): tooltip flicker on hover

packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/drawer/src/react/index.js, packages/drawer/stories/index.js
See #268
This moves the aria-label to the button element and allows for adding a custom label suffix.
- This was pointed out from the recent a11y audit (item 122). Allowing for a custom label allows us to give more context for what's in the drawer.
- This _could_ be seen as a breaking change but unsure if anyone is relying on that label being on the other element. We suspect that this shouldn't be a problem.
- We considered making this a callback to allow for more control but felt that this would be easier to set up.
- Added a story to verify.
=> drawer: allow custom aria-label

packages/dropdown/src/css/index.js
- Fixes #278 
- Fixes issue where the dropdown overlay was not covering the entire page so
the dropdown would not always close when clicking outside of the open menu.
- Chose a z-index of `970` for the overlay because we want it to cover prism (the sidebar has a z-index of `960`)
- Chose a z-index of `980` for the menu so it appears above the overlay.
1. Add a dropdown to a page
2. Add an element later in the DOM with `position: relative`
3. Open the dropdown
4. Click the other element and/or Prism - the dropdown should close
=> dropdown: increase dropdown overlay z-index

packages/textinput/package.json, packages/textinput/src/css/index.js, packages/textinput/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
Fixes issue where the textinput's focus ring was not showing if it was in a
container that had a background. Fix was to give the component its own z-index
stacking context by adding a z-index of 0.
Fixes #283 
- Add a textinput to a container that has a background.
- Focus the input - the focus ring should show up.
=> textinput: fix focus ring not showing

packages/button/.storybook/center-decorator.js, packages/button/.storybook/config.js, packages/button/src/css/index.js, packages/button/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/button/src/react/__specs__/storyshots.spec.js, packages/button/stories/index.js
fixes: #290
The button had two pseudo elements that were used to display our focus state. One of the pseudo elements was the entirety of the button background and defined a theme specific background color. This caused the `flat` appearance to have a background color on focus that was unwanted (#290).
I removed the `:after` pseudo element and updated the styles for the `:before` pseudo element to use a border only. Originally, through the use of two pseudo elements, we were able to achieve a nice rounded inner border on the focus outline that matched the rounded corner of the button. This change results in a less than ideal inner border rounding because i don't have a second pseudo element to overlay over the first to give the illusion of a rounded inner border.
I also introduced a new …
=> button: update focus styles to allow transparent backgrounds

packages/storybook-addon-theme/package.json, packages/storybook-addon-theme/src/index.js, packages/storybook-addon-theme/src/swatch.js, packages/storybook-addon-theme/src/theme-panel.js
`storybook-addon-theme` depended on the `<Button />` and the `<Button />` depended on `storybook-addon-theme`. This caused a circular dependency
- I removed the `<Button />` dependency
- I added a new ui in the theme panel to switch themes - just for fun
=> storybook-addon-theme: remove Button circular dependency

dangerfile.js
the danger rule for ensuring a reviewer on the pr isn't being used and is just noise at this point. i removed it
resolves #429
=> ci: danger - remove pr reviewer rule

packages/site/pages/components/emptystate.js
- Fix a spelling error in the documentation
Not applicable
Not applicable
=> emptystate : fix spelling error in documentation

packages/dialog/src/css/index.js, packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/dialog/src/react/index.js
Inner elements with transition, such as Switch would cause the entire
Dialog to repaint, but only:
- In Mac (Retina laptop screen only, OK in external monitor on same
computer)
- In Chrome/Brave (Chromium)
Fixes #473
=> fix(dialog): remove underlay animation to remove blink

packages/card/src/css/index.js, packages/card/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
- ActionBar needs a z-index > 0 because it may contain an ActionMenu that
overflows the card. The z-index will prevent the menu from going behind other
cards.
- Set pointer-events on ALL children of action-bar to be `all` so users
can interact with them. Allowed us to remove the pointer-events on
ActionBar buttons specifically.
Before: 
After:
Add some element to an ActionBar that overflows the card (ex: ActionMenu). Notice that the action-menu no longer goes behind the next card. It appears on top instead.
=> card: fix action-bar z-index & pointer events

packages/row/src/react/index.js, packages/row/src/react/use-match-media.js
safari needs the `screen` keyword in the media query. it also doesn't support `addEventListener` on the `MediaQueryList` so i fell back to the more widely supported `addListener`
=> fix(row): issues with safari and matchmedia

packages/prop-types/src/__specs__/element-of-type.spec.js, packages/prop-types/src/element-of-type.js, packages/prop-types/src/utils/index.js
When the validator receives a prop that happens to be a circular json, JSON.stringify will throw an error, and as stated on prop-types docs you can't throw inside a PropTypes.oneOf validator.
It happened to me while using `ActionMenu` with multiple `ActionMenu.Item`, the children was an array of elements and failed on stringify due to a circular json.
In my specific case, the `PropTypes.oneOf` will validate as ok if the stringify don't throw.
Probably the message `with value ${JSON.stringify(...)}` is not that pretty for this circular json situation (you can test it by passing multiple ActionMenu.Item and a non ActionMenu.Item to an ActionMenu).
Another approach is to try-catch the `JSON.stringify` but I don't know how the `with value xxx` message should look like in this case.
Render an …
=> prop-types: workaround circular json error

packages/breadcrumb/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/emptystate/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/errors/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/layout/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/textinput/src/css/index.js, packages/textinput/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
Fixes: #457
Apparently IE needs to know the vert positioning for position: absolute
element.  The other browsers seemed to do fine with just align-items:
center on the flex container
=> fix(textinput): [ie11] vert center icon

packages/table/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/table/src/react/index.js
Fixes: #467
Problem was introduced when we created the Theme HoC.  Classic coupling to implicit APIs.
=> fix(table): align column headers with rows that are tables

packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/radio/src/css/index.js, packages/radio/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/radio/src/react/button.js, packages/radio/src/react/index.js
Fixes: #458
Could not get to the bottom of why only IE did this.  It has something
to do with the Halo positioning.  Think it's related to IE's treatment
of splitting up the flex space.  Instead of flexing, just
display-inlined the circle and label.
=> fix(radio): [ie11] dont collapse margin on label

packages/note/src/css/index.js, packages/note/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/note/src/react/__stories__/index.story.js
Storybook wasn't showing this as a problem.  The ref site was.  The h2 I tried was too big.  This keeps it the same size.
I also think that Text.Heading is probably not common to be used, since it is for styling/sizing.  Instead, Note users will likely use h2/whatever directly for doc hierarchy use.
=> fix(note): maintain heading size with h1, etc

packages/site/pages/components/note.js
First commit fixes the errors (see the Example.React `includes`).
2nd commit is just trying to simplify the examples to highlight the prop specific to the section.
=> site: note errors

packages/site/pages/patterns/voice-tone.js
I adjusted the interleaving.  
It goes from this, which seems squeezed for space:
To this:
(Both look the same on mobile)
=> refactor(site): interleave voice and tone guidelines without columns

packages/site/pages/design-assets.js
The screenshot image of the UI kit was broken due to the removal of the design-system-assets repo.
Also removed the links to Figma help articles on using Team Libraries and Color & Text styles since they aren't really necessary anymore.
=> refactor(site): remove broken UI kit image and Figma help links

packages/banner/package.json, packages/banner/src/css/index.js, packages/banner/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/banner/src/react/__specs__/index.spec.js, packages/banner/src/react/__stories__/index.story.js, packages/banner/src/react/index.js, packages/site/pages/components/banner.js, packages/site/pages/components/button.js
- resolves #665
`Banner` now includes `Banner.Button`
I tried out a couple different approach but was hitting issues with css specificity in regards to the button styles. Our glamor setup was making it really difficult to fix the css order and specificity. I opted to create a new subcomponent(`Banner.Button`) which I feel is the best way to ensure the correct styles are applied. I also prefer this approach to encapsulate and ensure the right type of button is used.
=> feat(banner): add button component

packages/site/pages/components/actionmenu.js
To bring clarity to this question:
> Hey there — basic question perhaps, but does BelowLeft in the first in-app example here refer to something in the design system? https://design-system.pluralsight.com/components/actionmenu
=> site: add imports to example

packages/icon/src/react/__stories__/index.story.js, packages/icon/src/svg/caret-alt-down.icon.svg, packages/icon/src/svg/caret-alt-left.icon.svg, packages/icon/src/svg/caret-alt-right.icon.svg, packages/icon/src/svg/caret-alt-up.icon.svg
this was a request from gitprime. we already use this icon in the Dropdown but there isn't a version that is exposed in the Icons package. Gitprime would like these icons as they built out some custom components
=> feat(icon): alternate caret icons

packages/site/src/ui/example/react.js, packages/site/src/ui/theme-toggle.js
I adjusted the position of the theme toggle to move it closer to the top-right edge of the example div, and added more padding to the top & bottom of the example div so there would be no overlapping of the theme toggle and the examples.
=> refactor(site): adjust examples to prevent theme toggle overlapping

packages/link/react.d.ts
- Fixes the TypeScript declaration file for the `Link` component.
- This fixes the `appearances` reference described in the docs, eg. `Link.appearances.subtle`
The current declaration file does not include a reference to appearances in the `Link` export and should have the `Component` updated to `FunctionComponent` to allow `children` props.
Import `Link` into a `.tsx` file and use with a React component. TypeScript should no longer throw the following error:
```
Type '{ children: Element; appearance: any; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
Property 'children' does not exist on type 'IntrinsicAttributes & LinkProps'.ts(2322)```
=> fix(link): fix link typescript declaration file

packages/collapsible/src/__specs__/index.spec.js, packages/collapsible/src/index.js
1. Fixes close animations not working. The bug was caused by the height
not being set to the calculated auto height before being set to zero. Fixed
by not setting height to 0 before calculating the height.
1. Fixes the container not resizing with its content when it starts open. The
bug was caused by the height not being set to "auto" when it starts opened.
Fixed by resolving waitForHeightTransitionToEnd() if container is already at
target height.
1. Fixes the drawer breaking if user opens while it's closing or vice versa.
The bug was caused by not checking if the collapse was in the expected
state after the animation finishes. Fixed by checking the measured height
of the element after the animation finished and only doing close/open cleanup
code if the container is closed/opened.
1. When …
=> collapsible: animation & height issues

packages/layout/src/css/aside-layout.js, packages/layout/src/css/equal-column-layout.js, packages/layout/src/css/index.js, packages/layout/src/css/page-heading-layout.js, packages/layout/src/css/page-width-layout.js, packages/layout/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/layout/src/react/__stories__/index.story.js, packages/layout/src/react/index.js, packages/layout/src/react/page-width-layout.js, packages/site/pages/components/layout.js
Adds new LayoutPageWidth component
Supports:
- Constrains max width when prism won't
- Standard page-level gutters = 24px; 48px above 768px
- Float in center space
=> Layout page width

packages/icon/package.json, packages/site/pages/components/icon.js
Treeshaking for Icons is not be working. After creating a test project I concluded it's two things adding `sideEffects: false` to our repo and `optimization: {usedExports: true,}` to a webpack config for webpack 4. As for Parcel I haven't tested yet but according to their docs just the sideEffects part is needed only.
=> feat(icon): enables treeshaking when used by parcel or webpack

packages/core/css/colors-2020.module.css, packages/core/css/index.css
In temp location, for use today.  Later, will move to override permanent
location, as a breaking change.
Meant to sync js additions to css.  Keep in sync with js additions
thereafter.
Resolves: #780
=> feat(core): add 2020 colors as css

packages/viewtoggle/package.json, packages/viewtoggle/src/css/index.js, packages/viewtoggle/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/viewtoggle/src/react/index.js
2020, baby!
Besides just the color *conversion*, there were some visual changes in figma vs the code.  Perhaps I shouldn't have made those, because, thinking about it, if it's happening here, this probably won't be the last component to have this issue.
The color conversion shouldn't have to be visual maintenance at the same time, though it's probably ok to make a few adjustments if it doesn't gum up the PR or slow down this color conversion.
For instance, this component now looks different between themes.  It has new borders, and it dropped a shadow.  That is, if I read the diffs right in the PR.
@sweeting this is my first conversion, so I'm interested in getting your eyes on this too so I don't continue to make the same mistakes.  
Thanks, all!
=> refactor(viewtoggle): apply 2020 color palette

packages/verticaltabs/src/css/index.js, packages/verticaltabs/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/verticaltabs/src/react/index.js
Removed the bg color for the container per Brian.  We found the bg when converting colors.  There's no bg in figma.  There might be context around this that I'm missing.
=> refactor(verticaltabs): apply 2020 colors

packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/switch/package.json, packages/switch/src/css/index.js, packages/switch/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/switch/src/react/index.js
util/transparentize removed -- just another case where it seems we could do w/o;  small size switch had the "thumb" changed from 12px to 10px.  New border on unchecked state. Orange color made blue in anticipation of later removal of orange option.  Waiting on that later removal change so that Brian can make a determination if we want to go from 2 options (green/blue) down to just one, essentially removing the color prop.
=> refactor(switch): apply 2020 color palette

packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/drawer/src/react/__stories__/index.story.js, packages/row/package.json, packages/row/src/css/index.js, packages/row/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/row/src/react/__stories__/index.story.js, packages/row/src/react/index.js, packages/row/src/vars/index.js, packages/site/pages/components/drawer.js, packages/site/pages/components/row.js
In response to a request from Will
https://pluralsight.slack.com/archives/C70HPSJPP/p1579719708014300o
His use case is wanting to use another icon button that is provided as official widget from another BC.
This solution was in consultation with @sweeting .
=> row: Remove Row.Action, use DS Button instead

packages/icon/src/css/index.js, packages/icon/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/icon/src/react/__stories__/index.story.js, packages/icon/src/vars/index.js, packages/site/pages/components/icon.js
Removed a bunch of colors with Brian.  Breaking change release.
Kept only most likely icon colors:
- Text Icon
- Primary action, without semantics
- Statuses, without semantics
=> icon: apply 2020 colors

packages/datawell/src/css/index.js, packages/datawell/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
When you pull this up, will you please see if storybook will show you a theme switcher on datawell stories?
I didn't get one and didn't visually test this on light theme.
If you have this problem, I'll consider it not just a fluke of my env, and jump back on to troubleshoot it more.
=> refactor(datawell): apply 2020 colors

packages/dialog/src/css/index.js, packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/dialog/src/react/__stories__/index.story.js, packages/dialog/src/react/index.js, packages/site/pages/components/dialog.js
- add site doc for showing dialog in context
- fix doc link
- fix dialog to show tail (was regression from overflow support a while back).  Solution is to have an inner div to handle scrolling.  This solution now doesn't automatically move the close button the left when a scrollbar is present.  For this reason, I increased the close button margin generally.  I want to double check this, design-wise, with @sweeting .  There may be better alternatives.
=> dialog: fix tail

packages/badge/src/css/index.js, packages/badge/src/js/index.js, packages/badge/src/react/index.js
An attempt to make it more readable.  See last commit only.  Merge after #829.
=> badge: Simplify the css selector utility naming

packages/core/css/colors-2020.module.css, packages/core/css/colors.module.css
Fix to address Kristie's discovery
https://pluralsight.slack.com/archives/C70HPSJPP/p1580402336051300
Should match docs var names.
=> fix(core): remove 2020 from color css var names

packages/core/css/colors-2020.module.css
inline css vars because our build pipeline can't handle them when outputting sass files
fixes: #869
NOTE: i tried to update the build(postcss) so that i inlined css variables but couldn't figure it out....so i just did it in the src
=> fix(core): export valid sass variables

packages/build/postcss/postcss-css-var-selectors.js
resolves  #928
css was building incorrectly this resolves this by  creating a rule and appending the declaration to it.
=> fix(build): corrects postcss-css-var-selectors.js

package-lock.json, packages/starrating/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/starrating/src/react/__specs__/index.spec.js, packages/starrating/src/react/star.js
- Amber pointed out on the search site that interacting with the star rating through a screen reader is quite hard at the moment, because each star icon is read aloud before the label stating the actual rating is read. This change makes it so that the star icons are hidden as long as they are not interactive.
- I did not hide the stars when an `onChange` was present because in that context they are used as buttons
- Is there a reason that the individual stars should not be aria-hidden?
- Running the StarRating tests validates that the stars are in fact hidden
- Screen reader experience validated with NVDA/firefox in the storybook tests
=> StarRating: added aria-hidden to stars in star rating when not editable

postcss.config.js
Build has been broken for some time:
https://teamcity.vnerd.com/viewLog.html?buildId=777195&buildTypeId=Platform_DesignSystem_DesignSystemBuildDeploy&tab=buildLog&_focus=28812
Reporting:
Cannot find module 'postcss-import' from '/opt/teamcity/work/741c7bcb4a5d8ff4/packages/site/'
Site doesn't need postcss afaik or can remember.  Trying to figure out what the root postcss.config.js was used for, I decide it was unused.  
Core and normalize use postcss in their build
Postcss is used in core, normalize and build packages.  They seem to have independent package.json deps and postcss.config.js files or other custom postcss usage.
core, normalize, a component using the build package, and site still build
=> fix(site): rm root postcss.config.js

packages/site/pages/components/typeahead.js
Resolves #945
- Make it obvious that typeahead suggestion label and value are independent.
- Value prop exists.  Just wasn't documented.  
- Matches HTML native attrs quite well (eg, <select />)
- Load ref site locally
=> Add typeahead sugg doc

packages/site/pages/core/color.js
The js variable names for border colors on the docs site are:
colorsTextIcon.highOnLight / colorsTextIcon.lowOnLight
colorsTextIcon.highOnDark / colorsTextIcon.lowOnDark
The values should be:
colorsBorder.highOnLight / colorsBorder.lowOnLight
colorsBorder.highOnDark / colorsBorder.lowOnDark
Resolves: #994
=> docs(site): correct js variable names on border colors

packages/banner/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/breadcrumb/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/button/src/css/index.js, packages/button/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/emptystate/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/errors/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/form/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/layout/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/row/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/searchinput/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
Changed label & icon colors in flat buttons to "low" to match Figma.
Also made a tweak to the active state animation which uses `scale` instead of `translateY`, which I think is just slightly nicer. :)
=> refactor(button): use low color on flat button text/icon to match figma

packages/circularprogress/src/index.d.ts
This bug gives TypeScript users a compile error when importing `CircularProgress`
The problem is that you can't implement a function in a `.d.ts` file. In [#973](https://github.com/pluralsight/design-system/pull/973) we changed the `.d.ts` to implement and use a `keyMirror` function. This isn't valid. I should have run a typecheck locally to see this but failed to.
The fix just goes back to enumerating the sizes explicitly.
- Storybook runs locally without any type errors
=> CircularProgress: fix .d.ts problem which fails build for TS users

packages/navitem/src/react/__specs__/__snapshots__/storyshots.spec.js.snap, packages/navitem/src/react/__stories__/index.story.js, packages/navitem/src/react/common.js
This is really the main use case for bar style overrides. We show colored bars per product when the navitem is selected.
=> Style bar override on selected NavItem

packages/drawer/rc/index.js, packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
In regards to https://pluralsight.slack.com/archives/C70HPSJPP/p1595369904332500. Need this for a codepen fork. Modified the Drawer RC slightly removing unnecessary div and exposed useDrawerContext hook
=> feat(drawer): exposes underlying util useDrawerContext of drawer

packages/tab/src/index.d.ts, packages/tab/src/react/list-item.js
By making it a string typescript was not allowing the following content:
```
My items (50)
```
where 50 is a `number`. By changing it to `React.ReactNode`, that case is fixed and we now match the standard `PropsWithChildren` type in React:
```typescript
type PropsWithChildren<P> = P & { children?: ReactNode };
```
**I do notice that the `PropTypes` for the `ListItem` only wants a `string` - can that be updated?**
https://github.com/pluralsight/design-system/blob/dcf5395bee91dc24cd03e74dbcd100d30fa8025e/packages/tab/src/react/list-item.js#L55
=> [tab]: Update Tab.ListItem type to use ReactNode as children

packages/site/pages/components/dialog.js
Changed the style of secondary actions in the dialog examples from stroke to secondary.
=> docs(site): update secondary button style in dialog examples

packages/site/pages/components/appframe.js
the appframe made sense for me at the time to do in codesandbox instead of our normal docs because it's more involved and i wanted it on it's own page. now i'm not so sure...thoughts?
=> docs(site): provide sandbox for appframe

packages/navitem/src/css/index.js, packages/navitem/src/react/__specs__/__snapshots__/storyshots.spec.js.snap
Dunno if this changed in figma after the initial implementation or if it was mistranslated originally.  Anyway, now figma is showing navitem with marginTop 4px. This intros that. Should help with vertical centering w/in a navbar.
=> NavItem MarginTop

packages/actionmenu/package.json, packages/actionmenu/src/react/index.js
Fix the following proptype warning``Failed prop type: Invalid prop `children` supplied to `ActionMenu.Menu`.``
=> fix(actionmenu): proptype on menu loosened

docs/package-lock.json, docs/package.json, docs/src/components/mdx/code-block.module.css, docs/src/components/mdx/code-block.tsx, docs/src/pages/index.mdx
- Wanted to author in markdown since this is the common case for code authoring in docs
- Chose code block in markdown because it allows an opening and closing symbol
-  Chose a --- / hr symbol to split examples
- Downside to markdown is lack of rich data structure. Best idea so far: in a following PR, parse jsdocs for each example to parse out title and description
=> Example switcher

docs/src/components/code-block/examples.tsx, docs/src/components/code-block/index.tsx
just a small glow up that removes the trailing line in code examples
before:
after:
=> strip example whitespace

docs/src/components/code-block/examples.tsx, docs/src/pages/index.mdx
proposal: change the delimiter for segmenting examples in the code example switcher to be easy to read
`---` is used for frontmatter...so i'm thinking that `===` is different enough to make the codeblocks easier to understand
=> feat(docs): change switcher delimiter

docs/src/components/code-block/examples.tsx, docs/src/components/code-block/styles.module.css, docs/src/components/mdx/index.module.css, docs/src/components/mdx/index.tsx
=> fix heading alignment in example switcher

packages/verticaltabs/src/react/item.js
- `onClick` functions set on `<VerticalTabs.Tier1.Header />` components are overridden if the tier is collapsible. This change calls the custom `onClick` if provided after toggling the tier.
- To get around this problem I'm currently using an `onClick` on the tier1 component itself but that gets called when the child nav items are clicked too. I only want it to be called when the tier is expanded/collapsed.
- Add an onClick function to a collapsible tier1's header. Verify the fn gets called when clicking on the header.
=> verticaltabs: allow custom onClick on tier1 header

docs/gatsby-node.js, docs/src/components/frame/frame.tsx, docs/src/templates/example-frame.module.css, docs/src/templates/example-frame.tsx
Just an idea. I like it better because it's not wrapped up in frame and doesn't use the window.location. And the *template* switching is where templates are first chosen, in createPage().
=> Alternative approach to examples template selection

yarn.lock
Maybe this will work better.
yarn list prismjs looks good
yarn list node-fetch less sure:
```
~/dev/design-system on  yarnupgrade2 [$] took 2s ❯ yarn list node-fetch
yarn list v1.21.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ graphql-request@1.8.2
│  └─ node-fetch@2.1.2
├─ isomorphic-fetch@2.2.1
│  └─ node-fetch@1.7.3
└─ node-fetch@2.6.1
✨  Done in 1.80s.
```
Top-level dep is good at 2.6.1. Supdep is very low at 1.7.3.
=> build: yarn upgrade in root

package.json
Seems to work.
`yarn audit` before is loud. After doesn't mention these two issues.
Not sure why GH mentions these two but not the others in yarn audit.
=> build: fix secvulns by forcing package resolution

docs/src/components/frame/frame.module.css
Like Goldilocks, 1200 was too wide, 800 was too narrow, hoping 1000 is just right.
=> refactor(docs): adjust max-width of main

packages/errors/package.json
using babel is kind of a hack so we can fix the error and get a working package out. i'd like to double back soonish to convert this component to a ts only solution
resolves #1361
=> build(errors): revert to using babel so we can use the import-all macro

docs/src/components/mdx/index.module.css
During the build, glamor and postcss are compiled and added to the initial html render in two different ways. postcss is reference through link in a css file. glamor includes it's styles in a style blob that is part of the initial render and they hydrated. because the heading style specificity is the same from the glamor heading style and postcss heading style override - the last style on the page wins. which happens to be the glamor style - which is incorrect.
there are a couple options to fix this:
- dump the gatsby plugins and build up our own ssr+babel+webpack configs for gatsby and babel
- create a postcss plugin that prepends a specifity increase hack to each postcss style
- https://github.com/MadLittleMods/postcss-increase-specificity
- add a specifity hack to styles as needed.
i …
=> fix(docs): increase heading specificity

docs/src/components/frame/frame.module.css
Resolves #1399
Not sure why the overflow: auto was there.  Since I couldn't think of a good reason doesn't mean that there isn't one.  Anyone have some more context on this?
=> fix(docs): rm main body scrollbar

docs/src/content/components/dialog.mdx, packages/dialog/src/react/index.tsx
Portal seems to makes sense for a modal always, right?
Fixes the problems of
- Modal overlay in docs (and hopefully everywhere else; seems like we've had reports of this being problematic due to avoiding z-index and style overriding being generally hard)
- Docs button row alignment
BREAKING CHANGE: Modal always renders in a portal. Made breaking change
since it's uncertain whether this change in layout will affect users
visually.
^ overkill?
Reported here:
https://pluralsight.slack.com/archives/C70HPSJPP/p1605227641202600
=> render modal dialog in portal always

packages/typeahead/src/react/index.tsx, packages/typeahead/src/react/menu.tsx
I wanted to drive with a test something like this, but I never got it working.  I couldn't figure out why input's value was never updated on Enter.  All the elements were found, just seemed like that final step didn't show up for some reason.  Kind of funny there are no other keyboarding tests in the suite either.  My current best guess is there's some sort of timing problem with the Position wrapper. 
``` 
import { logDOM } from '@testing-library/dom'
import userEvent from '@testing-library/user-event'
it('selects the focused element upon pressing enter', async () => {
const { getByLabelText } = render(
<Typeahead label="inputlabel">
<Typeahead.Suggestion>primo</Typeahead.Suggestion>
<Typeahead.Suggestion>second</Typeahead.Suggestion> …
```
=> fix(typeahead): allow selection with tab, enter and space keys

packages/datepicker/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/datepicker/src/react/__specs__/index.spec.tsx, packages/datepicker/src/react/index.tsx, packages/form/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- Inputs already textbox in accessibility tree
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/textbox_role
- But needed better, now individual labelling
- Following WAI subfield labelling suggestion
https://www.w3.org/TR/WCAG20-TECHS/ARIA14.html
- Using getByRole prioritized testing-library query
https://testing-library.com/docs/guide-which-query/
- getByRole(roleName, { name }) is non-intuitive: name is a label, not
an html attr
https://testing-library.com/docs/dom-testing-library/api-queries/#byrole
=> refactor(datepicker): make subfields available to accessibility tree

docs/src/content/components/dropdown.mdx, packages/dropdown/src/js/index.ts, packages/dropdown/src/react/__specs__/storyshots.spec.ts, packages/dropdown/src/react/__stories__/index.story.tsx, packages/dropdown/src/react/index.tsx
Search team is trying to mock uniqueId's for snapshot stability, similar to what we have done.  The problem is that jest.mock requires a package name to mock a dependency. By the time we build, this package name information is not available for consumers to reach down into our code and identify the uniqueId function. This exposes uniqueId on Dropdown directly.
Could have done this through a static. The override method then would have been similar, using jest.mock.  Chose instead to simply use a prop. This is simpler and doesn't require mocking.
=> expose dropdown's uniqueId function for test

docs/src/components/code-block/package-map.ts, docs/src/components/side-nav/index.tsx, docs/src/content/patterns/page-headers.mdx, docs/src/content/patterns/page-headings.mdx
- Used frame labels in figma so that designers and developers are hopefully talking the same language.
- Called the last pattern in figma "Basic alternative". It was unlabeled in figma.
- Seems like some explanatory text would be useful. I see patterns without context. Oooh, I like this one, it has all the widgets I need. For instance, how would one decide which of the "basic" patterns he should use? One has an icon and fewer buttons, but that doesn't seem to indicate enough to be educated about the existence of 2 similar choices.
=> add page heading patterns to docs

docs/src/components/code-block/actions.tsx
- I'm assuming that `invariant` must come from the `devDependencies` present. It might not be. We could just list it as a new dependencies, as that seems to solve the problem manually within codesandbox.  Waddya think?
- I think the problem is that devDependencies don't show up in the sandbox. https://github.com/codesandbox/codesandbox-client/issues/2794
=> fix sandbox dependencies

packages/core/css/type.module.css, packages/core/js/type.ts
We'll eventually want remove the old vars, but until then, I used the comments to indicate which sets are deprecated.
=> refactor(core): indicate deprecated vars in comments

packages/carousel/src/react/__specs__/storyshots.spec.tsx, packages/carousel/src/react/__specs__/use-unique-id.spec.ts, packages/carousel/src/react/__stories__/index.story.tsx, packages/carousel/src/react/index.tsx, packages/carousel/src/react/use-unique-id.ts
We had trouble mocking out `uniqueId` for snapshot testing. Looking at how you do it for your tests, we tried doing something similar:
```typescript
jest.mock('@pluralsight/ps-design-system-carousel/dist/esm/js/utils', () => ({
uniqueId: jest.fn().mockImplementation(prefix => prefix + '12345')
}))
```
But that didn't seem to work for us. Any ideas? I'm not sure if you can mock things out this way, or if you'd have to mock out the entire package.
Otherwise, allowing a custom `uniqueId` function to be passed in seems to be the friendliest solution, as we did for the dropdown (https://github.com/pluralsight/design-system/pull/1522)
=> feat(carousel): add custom uniqueId prop for testing

docs/src/content/components/badge.mdx, packages/badge/src/css/index.ts, packages/badge/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/badge/src/react/index.tsx, packages/badge/src/vars/index.ts
`badge`
- Breaking change: color 'gray' is now called 'neutral'
- All styles meet WCAG AA contrast guidelines
- New styling for subtle appearance on dark to be more consistent with subtle appearance on light (filled instead of borders)
`docs`
- Change references from 'gray' to 'neutral'
- Correct default values in types table
=> Badge design & a11y tweaks

packages/datepicker/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/datepicker/src/react/__stories__/index.story.tsx
Only affected the one MultiDate Calendar story. By init'ing the calendar with a `date` param, this was solved. Also threw in date selection to make the story more illustrative of its feature.
Resolves #1641
=> datepicker: stabilize storyshots

docs/src/content/components/datepicker.mdx
Someone used a literal drop in for the old DatePicker, but it didn't work the exact same. This hedges the language more.
=> docs: update datepicker caveats

packages/navuser/package.json, packages/navuser/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/navuser/src/react/__stories__/index.story.tsx, packages/navuser/src/react/index.tsx
The click being swallowed was in a very specific instance, as seen by
the added story. Still not sure why the onClick was not being triggered.
Before this commit, would take an extra click (click navuser to click
off and closer actionmenu due to document close listeners, then another
click to open the navuser). The change makes all that happen in one
click.
Resolves: #1656
=> fix(navuser): avoid swallowing click

packages/table/package.json
Usages are in src/:
src/react/index.tsx
13:import invariant from 'invariant'
182:      invariant(title, msg)
src/react/sticky.tsx
3:import invariant from 'invariant'
14:  invariant(ref, 'ref is required')
Nothing in the usage seems to suggest it needs to a peer dep:
https://www.npmjs.com/package/invariant
Easiest way forward seems to be make this a production dependency.
=> table: move invariant to dependencies

docs/src/content/components/searchinput.mdx
Resolves: #1653
I'm not sure why enterKeyHint tsc error is coming up in Codesandbox and in the Content Libraries project. It's not coming up when building the DS.
It seems that should be an optional prop and available to use in @types/react:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48971/files#diff-32cfd8cb197872bcba371f5018185d2e75fa540b52cda2dd7d8ac12dcc021299R2095
I added an enterKeyHint section to the docs. If we had an a11y for the component, I think it would go in there, since it has to do with ux and semantics.
I added the other notes about "may have TS error" with the caveats to assist any other dev who may encounter this.
=> feat(docs): add enterKeyHint section to searchinput

packages/select/package.json, packages/select/src/index.ts
-  The `build` script for the select component looks like it was never implemented so we just copied it from another one
-  There was no default export
- Verify the package builds
- Verify you can use the default export in JSX and use the static vars off of it
=> select: fix build script and module default export

packages/menu/src/css/index.ts, packages/menu/src/react/ItemWithDescription.tsx, packages/menu/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/menu/src/react/__stories__/index.story.tsx, packages/select/src/css/index.ts, packages/select/src/react/index.tsx
=> fix(select): dropdown zindex added

packages/storybook-addon-theme/README.md, packages/storybook-addon-theme/src/components/tool.tsx, packages/storybook-addon-theme/src/hooks.ts, packages/storybook-addon-theme/src/index.tsx
- Adds ability to customize the default theme for each story
- Copied the way the [Background addon](https://github.com/storybookjs/storybook/tree/next/addons/backgrounds) in Storybook's addon-essentials works (but with a cleaner hooks approach!)
- [Set](https://storybook.js.org/docs/react/writing-stories/parameters) the `theme.name` parameter on a story to `light` and verify the component loads with the light theme and can be toggled back.
=> storybook-addon-theme: ability to set theme per-story

packages/select/src/react/useListbox.ts
- When a select menu is opened it starts intercepting, preventing default, and stopping propagation of all keyboard events because the key check is always returning true.
- Render a select
- Open the menu
- Verify you can tab around the page still
- Verify the button does not constantly steal focus when clicking/tabbing around the page
=> select: stop intercepting all key events

packages/tagsinput/src/css/index.ts, packages/tagsinput/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
- https://github.com/pluralsight/design-system/issues/1701
- Render a tagsinput
- create multiple pills so you see a scroll bar
- Verify the scroll is at right most end
=> tagsinput: fix scroll bar position when items/pills overflow 

packages/tagsinput/src/css/index.ts, packages/tagsinput/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/tagsinput/src/react/__stories__/index.story.tsx, packages/tagsinput/src/react/index.tsx
- Redo some layout to make tagsinput consistent with buttons and text inputs at 40px tall
- Fixes text input box being too tall which was adding extra space above the last row of tags
- Fixes placeholder being cut off because it wasn't flex-growing
- Adds "Empty" and "Multiple lines" stories
- The gutter around the edges of the box is 8px and the spacing between tags is 4px
- Verify the tagsinput component is 40px tall
- Verify scrolling a multi-line tagsinput looks correct (scroll bar in the right place, spacing around the edge of the box is correct, etc...)
- Verify a longer placeholder text no longer gets cut off
- Verify the space above the third row of tags is not larger than above the second row
=> tagsinput: match height of buttons & text inputs

docs/src/content/components/typeahead.mdx
=> fix(docs): options is required in typeahead

docs/src/components/frame/aside.module.css, docs/src/components/frame/frame.module.css, docs/src/components/frame/header.module.css, docs/src/components/motion/easing.module.css, docs/src/components/table-of-contents.module.css, docs/src/content/index.module.css
Removing the extra set of parens in the `@media` CSS rules fixed the issues with the docs always showing the mobile layout at all screen widths.
Closes #1737
=> fix(docs): remove extra parens in @media rules

README.md
The links under the "Get Involved" section of the readme were broken.
I found what appear to be the updated URLs.
=> fix(docs): update broken readme links

docs/src/content/components/datepicker.mdx, packages/datepicker/src/react/__specs__/index.spec.ts, packages/datepicker/src/react/utils.ts
- Currently, the display format for is hard-coded to use 'MM/dd/yyyy'
- With this change, someone using this function can pass their own date format string to control how the date is displayed and entered in the text field.
- I added an optional `dateFormat` parameter to the `useDateSelectChange` and `useRangeSelectChange` functions. It defaults to the same format that was already used, so it should be backward compatible.
- The input is validated with a regex `/[0-1][0-9]\/[0-3][0-9]\/[0-9][0-9][0-9][0-9]/`, which doesn't catch some of the nuances of dates (for example, Feb 30th is invalid, but matches the regex)
- I replaced the regex test with the `isMatch` function from date-fns. Any RangeError thrown by that function is caught, since it typically means the date string doesn't match …
=> feat(datepicker): custom date format

packages/carousel/src/react/__specs__/index.spec.tsx
I thought there would be problems exposed by the test, as seen during
the CSF conversion, but I ran the test several times and ways, and I
could not get axe to detect any errors. So, I guess just enable the
tests that were previously written and keep them running.
Resolves: #1755
=> test(carousel): enable axe test

docs/src/content/components/card.mdx, packages/card/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/card/src/react/__specs__/index.spec.tsx, packages/card/src/react/__stories__/index.story.tsx, packages/card/src/react/index.tsx
Among a couple other related adjustments:
- refactor(card): props extend react.htmlattributes for div
- test(card): fix tsc error in test
- feat(card): allow alt prop to Card.Image
- test(card): resolve axe bug of images without labels in stories
- refactor(docs): add aria-label to Card.Image examples
=> card axe fix for img labels

packages/appframe/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/breadcrumb/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/button/src/css/index.ts, packages/button/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/button/src/react/__stories__/index.story.tsx, packages/button/src/react/index.tsx, packages/datepicker/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/dialog/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/emptystate/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/errors/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/focusmanager/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/form/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/layout/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/navuser/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/row/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/searchinput/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/table/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap
This was working in the case where the state was not loading to start
and then switched to it. Now, it will work consistently whether it
starts loading or not.
Approach changed. Instead of measuring width, display invisible text to
maintain width during loading state.
Related:
https://pluralsight.slack.com/archives/C5CMEKH5Z/p1624282887087800
=> fix button display when loading on mount

packages/datepicker/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/datepicker/src/react/__stories__/index.story.tsx, packages/datepicker/src/react/datepicker.tsx
lol, sorry about the branch name. I was doing something else when I committed this and forgot to change branches.
- feat(datepicker): add value prop for controlled DatePicker
On this 2nd commit, please double check me, Edward. I don't know why this date would have been there. It's odd, so seems safe to delete. But, it's odd, so maybe I'm missing the point, and it's still required.
- refactor(datepicker): remove odd selected date default
=> add value prop to datepicker

docs/src/content/components/datepicker.mdx
From user doc walkthrough that we noticed this.
Brian, I'm not sure if this is the right place to put this, but I think it's the best at the moment. The DatePicker docs are not the common case in what they contain or how they're organized.
Resolves: #1837
=> add changelog link to datepicker doc

packages/text/src/css/index.ts, packages/text/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap
Line-height values for small, medium, large label components have been corrected to match Figma.
Resolves: #1852
=> text: fix incorrect label line-height values

docs/src/components/frame/frame.module.css, docs/src/components/table-of-contents.module.css
=> fix(docs): don't allow table of contents to overlay content on mobile

packages/textarea/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/textarea/src/react/__stories__/index.story.tsx, packages/textarea/src/react/index.tsx
Related to: 
https://pluralsight.slack.com/archives/C70HPSJPP/p1626281065135900?thread_ts=1626191988.133400&cid=C70HPSJPP
This won't be the last time this happens. React.HTMLAttributes, which we've recently standardized on, just doesn't have all the attributes for these kinds of HTML elements.
Resolves: #1934
=> fix(textarea): allow maxLength and textarea-specific props in TS

packages/normalize/css/index.css, packages/normalize/package.json, yarn.lock
Issue is that this normalize package didn't receive a breaking change,
but had it starting using core@9, which changed to dashified css vars.
These vars are in the global :root and used in this package. But we
don't want to ship that var change to people until they're ready. This
has probably been breaking pages (hopefully subtly?!) that have looser
version dependency on the normalize package.
After this, we want to go back to dashified, use core@9, do a major
version bump and then patch fix all latest components to peerDepend on
the latest normalize.
Related to #1947
Please second-guess my logic on this. I hate to have released what seems like a breaking change to users who weren't ready for it. I probably would hate thinking I did that then making a bigger mess trying to mitigate a …
=> fix(normalize): revert core back to camelCase variables

packages/normalize/package.json
Normalize should be browser ready. We don't want the postcss-loader for our users to have to respect our postcss.config.js in normalize builds.
=> fix(normalize): exclude postcss.config.js from node_modules

packages/avatar/src/index.ts, packages/button/src/index.ts, packages/icon/src/index.ts
Tools like MiniExtractPlugin were not respecting sideEffects: true on these files. They were removing the styles from final bundles. The reason is unknown, but making these files import then export like this seems to resolve the problem, avoiding the overly-eager treeshaking.
=> Fix export pattern to avoid treeshaking styles

packages/drawer/src/css/index.css, packages/drawer/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/drawer/src/react/index.tsx, packages/util/src/index.ts, packages/util/src/unique-id.ts
Brought in generateId from FormControl branch. Will be an eventual merge conflict.
Followed https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html
Switching Summary DOM el from div to button will surely create some bad HTML nesting eventually because we allow the pattern of Rows in Drawers. Maybe we shouldn't?
=> Make drawer keyboard accessible

docs/src/components/mdx/index.tsx, docs/src/components/usage.module.css, docs/src/components/usage.tsx, docs/src/content/components/dropdown.mdx
Brian, as I looked at this, I thought that the a11y module design I had made and what is accomplishable just with markdown were so close that I'd lean on the latter for the moment and see what we thought.
I think it's a fine experience. 
Two big reasons I like it: 1) It avoids having to deal with the API for a summary module. 2) Not having a set API allows for one-off descriptions of a11y as needed per component.
There are two commits. The first with the MDX capability. The second, giving an example on the Dropdown page. If I was you, and you end up liking this approach, I'd just copy the first commit into my own branch, ignore the 2nd commit and then close this PR when you're well on your way.
This is what it looks like rendered:
=> Accessibility section in docs

docs/src/content/components/avatar.mdx, docs/src/content/components/badge.mdx, docs/src/content/components/banner.mdx, docs/src/content/components/card.mdx, docs/src/content/components/carousel.mdx, docs/src/content/components/datawell.mdx, docs/src/content/components/icon.mdx, docs/src/content/components/note.mdx, docs/src/content/components/row.mdx, docs/src/content/components/table.mdx, docs/src/content/components/tag.mdx
Added a11y sections, Figma links, and reorganized contents of docs pages in the Content Display and Feedback nav sections.
=> Docs a11y - Content Display & Feedback pages

docs/src/content/components/circularprogress.mdx, docs/src/content/components/dialog.mdx, docs/src/content/components/emptystate.mdx, docs/src/content/components/errors.mdx, docs/src/content/components/featureflags.mdx, docs/src/content/components/linearprogress.mdx, docs/src/content/components/position.mdx, docs/src/content/components/screenreaderonly.mdx, docs/src/content/components/scrollable.mdx, docs/src/content/components/starrating.mdx, docs/src/content/components/theme.mdx, docs/src/content/components/tooltip.mdx
Add a11y sections, figma links, and reorg content structure of component pages in the Feedback and Utilities nav sections.
=> Docs a11y - Feedback & Utility component pages

packages/drawer/src/css/index.css
https://pluralsight.slack.com/archives/C70HPSJPP/p1630095874000800
=> fix(drawer): border-top on row on light-theme removed

.github/dependabot.yml
Dependabot keeps reporting security vulnerabilities for non-package workspaces (examples, etc.). Adding configuration to try and scope to only packages we are shipping.
=> ci: add dependabot.yml to scope checks to packages only

packages/datepicker/src/react/__specs__/__snapshots__/storyshots.spec.tsx.snap, packages/datepicker/src/react/__stories__/index.story.tsx, packages/datepicker/src/react/datepicker.tsx
closes #2026 
DatePicker was stealing focus from other inputs when sharing a page view. This PR solves that issue.
- Fire up ol' DatePicker SB and go to the "Example" option which mimicks the docs page
- DatePicker input should allow focus to itself and other inputs sharing the view without causing issues of each working independently and correclty
=> fix(datepicker): remove unnecessary forced focus

packages/dropdown/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/dropdown/src/react/button.tsx
fixes #1958
Adds missing a11y `aria-expanded` prop to the `button` component for Dropdown.
Open storybook for Dropdown and inspect via devtools. Will now see a `aria-expanded` attribute for the Button and will correctly update value according to open state.
=> fix(dropdown): add missing a11y attr for button

packages/checkbox/src/react/__specs__/__snapshots__/storyshots.spec.ts.snap, packages/checkbox/src/react/__stories__/index.story.tsx, packages/checkbox/src/react/index.tsx
closes #2035 
Checkbox component was logging syntax errors due to missing `onChange` prop perference.
Updates the components to favor `onChange` over `onCheck` to prevent console errors from being logged as well as releasing a  breaking change.
=> fix(checkbox): prefer onChange over onCheck

packages/core/package.json, packages/dropdown/package.json, packages/util/package.json
contributes to #2018 
Core, Dropdown, and Util packages were missing some devDeps which were breaking code sandboxes along with causing bad installs for people using Yarn Berry with PnP
Adds missing deps to packages.
=> fix: add missing deps to core, dropdown, and util packages

packages/storybook-addon-center/package.json, packages/storybook-addon-theme/package.json, packages/storybook-preset/package.json
Storybook addon packages had all dependencies installed as prod
Dependencies for these packages moved to dev, since they are only needed for building the package
=> deps: move all custom storybook addon deps to dev
